(function () {
  const NHM = "https://www.nhm.ac.uk/discover/dino-directory.html";
  const SMITHSONIAN = "https://naturalhistory.si.edu/explore/dinosaurs-fossils";
  const measurements = (length, height, weightKg) => ({ length, height, weightKg });
  const creature = (entry) => Object.assign({
    image: null,
    uncertainty: "Like every prehistoric reconstruction, some details may change when scientists find new evidence."
  }, entry);

  window.CREATURES = [
    creature({ slug:"tyrannosaurus-rex", name:"Tyrannosaurus rex", scientificName:"Tyrannosaurus rex", pronunciation:"tie-RAN-oh-SORE-us rex", meaning:"tyrant lizard king", type:"Dinosaur", group:"Theropods", period:"Late Cretaceous", age:[68,66], measurements:measurements([11.5,13], [3.5,4], [7000,9000]), diet:"Carnivore", movement:"Walked and ran on two powerful legs", countries:["Canada","United States"], regions:["North America"], fact:"Its deep skull and thick teeth were built to deliver a bone-crushing bite.", didYouKnow:"A large part of its brain was devoted to smell, helping it locate food.", source:NHM }),
    creature({ slug:"triceratops", name:"Triceratops", scientificName:"Triceratops horridus", pronunciation:"try-SERRA-tops", meaning:"three-horned face", type:"Dinosaur", group:"Ceratopsians", period:"Late Cretaceous", age:[68,66], measurements:measurements([8,9], [2.7,3], [6000,12000]), diet:"Herbivore", movement:"Walked on four sturdy legs", countries:["Canada","United States"], regions:["North America"], fact:"Its huge frill and three horns may have helped with display, defense, or both.", didYouKnow:"Triceratops had a parrot-like beak and batteries of teeth for slicing tough plants.", source:NHM }),
    creature({ slug:"stegosaurus", name:"Stegosaurus", scientificName:"Stegosaurus stenops", pronunciation:"STEG-oh-SORE-us", meaning:"roof lizard", type:"Dinosaur", group:"Stegosaurs", period:"Late Jurassic", age:[155,150], measurements:measurements([7,9], [3.5,4], [3500,7000]), diet:"Herbivore", movement:"Walked on four legs", countries:["Portugal","United States"], regions:["North America","Europe"], fact:"Two rows of plates ran along its back, while four long spikes armed its tail.", didYouKnow:"Scientists call the spiked tail a thagomizer.", source:NHM }),
    creature({ slug:"velociraptor", name:"Velociraptor", scientificName:"Velociraptor mongoliensis", pronunciation:"veh-LOSS-ih-RAP-tor", meaning:"swift thief", type:"Dinosaur", group:"Dromaeosaurs", period:"Late Cretaceous", age:[75,71], measurements:measurements([1.8,2], [0.5,0.7], [15,20]), diet:"Carnivore", movement:"Ran on two legs", countries:["China","Mongolia"], regions:["Asia"], fact:"It was a feathered predator about the size of a large turkey, not a movie-sized giant.", didYouKnow:"Each foot had a curved claw that was held off the ground while walking.", source:NHM, image:{ src:"../assets/images/dinosaurs/velociraptor.png", alt:"Illustrated reconstruction of a feathered Velociraptor", artist:"Fred Wierum", license:"CC BY-SA 4.0", licenseUrl:"https://creativecommons.org/licenses/by-sa/4.0", page:"https://commons.wikimedia.org/wiki/File:Velociraptor_Restoration.png" } }),
    creature({ slug:"brachiosaurus", name:"Brachiosaurus", scientificName:"Brachiosaurus altithorax", pronunciation:"BRACK-ee-oh-SORE-us", meaning:"arm lizard", type:"Dinosaur", group:"Sauropods", period:"Late Jurassic", age:[154,150], measurements:measurements([18,22], [9,13], [28000,56000]), diet:"Herbivore", movement:"Walked on four pillar-like legs", countries:["United States"], regions:["North America"], fact:"Its front legs were longer than its back legs, lifting its shoulders and neck high.", didYouKnow:"Its nostrils were on the front of its snout even though the skull opening sits high.", source:NHM }),
    creature({ slug:"diplodocus", name:"Diplodocus", scientificName:"Diplodocus carnegii", pronunciation:"dip-LOD-oh-kus", meaning:"double beam", type:"Dinosaur", group:"Sauropods", period:"Late Jurassic", age:[154,152], measurements:measurements([24,27], [4,5], [12000,16000]), diet:"Herbivore", movement:"Walked on four legs", countries:["United States"], regions:["North America"], fact:"A very long neck and whip-like tail made up much of its enormous length.", didYouKnow:"The name refers to paired bones underneath part of its tail.", source:NHM }),
    creature({ slug:"ankylosaurus", name:"Ankylosaurus", scientificName:"Ankylosaurus magniventris", pronunciation:"ang-KYE-loh-SORE-us", meaning:"fused lizard", type:"Dinosaur", group:"Ankylosaurs", period:"Late Cretaceous", age:[68,66], measurements:measurements([6,8], [1.5,1.8], [5000,8000]), diet:"Herbivore", movement:"Walked on four legs", countries:["Canada","United States"], regions:["North America"], fact:"Bony armor covered its back and a heavy club tipped its tail.", didYouKnow:"Even its eyelids may have contained small armor plates.", source:NHM }),
    creature({ slug:"spinosaurus", name:"Spinosaurus", scientificName:"Spinosaurus aegyptiacus", pronunciation:"SPY-noh-SORE-us", meaning:"spine lizard", type:"Dinosaur", group:"Theropods", period:"Late Cretaceous", age:[100,94], measurements:measurements([14,15], [4.5,5], [6000,7400]), diet:"Piscivore", movement:"Moved on land and was adapted for swimming", countries:["Egypt","Morocco"], regions:["Africa"], fact:"Its tall back sail and paddle-like tail belonged to a predator closely tied to water.", didYouKnow:"Cone-shaped teeth were well suited to grabbing slippery fish.", uncertainty:"Spinosaurus is known from incomplete fossils, so scientists still debate its posture and swimming style.", source:NHM }),
    creature({ slug:"allosaurus", name:"Allosaurus", scientificName:"Allosaurus fragilis", pronunciation:"AL-oh-SORE-us", meaning:"different lizard", type:"Dinosaur", group:"Theropods", period:"Late Jurassic", age:[155,145], measurements:measurements([8.5,10], [2.5,3], [1500,2500]), diet:"Carnivore", movement:"Walked and ran on two legs", countries:["Portugal","United States"], regions:["North America","Europe"], fact:"This large hunter had three-clawed hands and small horns above its eyes.", didYouKnow:"Many Allosaurus fossils have been found together at the Cleveland-Lloyd quarry in Utah.", source:NHM }),
    creature({ slug:"iguanodon", name:"Iguanodon", scientificName:"Iguanodon bernissartensis", pronunciation:"ih-GWAH-noh-don", meaning:"iguana tooth", type:"Dinosaur", group:"Ornithopods", period:"Early Cretaceous", age:[126,122], measurements:measurements([9,11], [3,4], [4000,5000]), diet:"Herbivore", movement:"Could move on two or four legs", countries:["Belgium","Germany","United Kingdom"], regions:["Europe"], fact:"A sharp thumb spike may have helped it defend itself or handle food.", didYouKnow:"It was one of the first dinosaurs ever named by scientists.", source:NHM }),
    creature({ slug:"parasaurolophus", name:"Parasaurolophus", scientificName:"Parasaurolophus walkeri", pronunciation:"pair-ah-sore-OL-oh-fus", meaning:"near crested lizard", type:"Dinosaur", group:"Hadrosaurs", period:"Late Cretaceous", age:[77,73], measurements:measurements([9,10], [3.5,4], [2500,5000]), diet:"Herbivore", movement:"Could move on two or four legs", countries:["Canada","United States"], regions:["North America"], fact:"Its long hollow crest connected to its breathing passages.", didYouKnow:"Models suggest air through the crest could make a deep, trumpet-like sound.", source:NHM }),
    creature({ slug:"pachycephalosaurus", name:"Pachycephalosaurus", scientificName:"Pachycephalosaurus wyomingensis", pronunciation:"PACK-ee-sef-ah-loh-SORE-us", meaning:"thick-headed lizard", type:"Dinosaur", group:"Pachycephalosaurs", period:"Late Cretaceous", age:[70,66], measurements:measurements([4.5,5], [1.5,2], [370,450]), diet:"Omnivore", movement:"Walked on two legs", countries:["United States"], regions:["North America"], fact:"The roof of its skull formed a rounded dome up to about 25 centimeters thick.", didYouKnow:"Scientists debate whether it bumped heads, shoved rivals, or used the dome for display.", uncertainty:"Its diet and the way it used its skull dome are both uncertain.", source:NHM }),
    creature({ slug:"carnotaurus", name:"Carnotaurus", scientificName:"Carnotaurus sastrei", pronunciation:"kar-noh-TAW-rus", meaning:"meat-eating bull", type:"Dinosaur", group:"Theropods", period:"Late Cretaceous", age:[72,69], measurements:measurements([7.5,8], [2.5,3], [1300,2100]), diet:"Carnivore", movement:"Ran on two legs", countries:["Argentina"], regions:["South America"], fact:"It had two thick horns above its eyes and extremely tiny arms.", didYouKnow:"Rare skin impressions reveal rows of pebbly scales and larger bumps.", source:NHM }),
    creature({ slug:"deinonychus", name:"Deinonychus", scientificName:"Deinonychus antirrhopus", pronunciation:"dye-NON-ih-kus", meaning:"terrible claw", type:"Dinosaur", group:"Dromaeosaurs", period:"Early Cretaceous", age:[115,108], measurements:measurements([3,3.4], [0.9,1.2], [70,100]), diet:"Carnivore", movement:"Ran on two legs", countries:["United States"], regions:["North America"], fact:"A large curved claw on each foot helped make it a formidable hunter.", didYouKnow:"Studies of Deinonychus helped change the old idea that dinosaurs were slow and sluggish.", source:NHM }),
    creature({ slug:"dilophosaurus", name:"Dilophosaurus", scientificName:"Dilophosaurus wetherilli", pronunciation:"dye-LOF-oh-SORE-us", meaning:"two-crested lizard", type:"Dinosaur", group:"Theropods", period:"Early Jurassic", age:[193,183], measurements:measurements([6,7], [1.5,2], [300,450]), diet:"Carnivore", movement:"Walked and ran on two legs", countries:["United States"], regions:["North America"], fact:"Two thin crests decorated its head, probably for display.", didYouKnow:"There is no fossil evidence that it had a neck frill or spat venom.", source:NHM }),
    creature({ slug:"coelophysis", name:"Coelophysis", scientificName:"Coelophysis bauri", pronunciation:"see-LOF-ih-sis", meaning:"hollow form", type:"Dinosaur", group:"Theropods", period:"Late Triassic", age:[216,203], measurements:measurements([2.5,3], [0.9,1], [15,25]), diet:"Carnivore", movement:"Ran on two legs", countries:["United States"], regions:["North America"], fact:"Its hollow bones and slim build made this early dinosaur lightweight and quick.", didYouKnow:"Hundreds of skeletons were discovered together at Ghost Ranch in New Mexico.", source:NHM }),
    creature({ slug:"archaeopteryx", name:"Archaeopteryx", scientificName:"Archaeopteryx lithographica", pronunciation:"ar-kee-OP-ter-iks", meaning:"ancient wing", type:"Dinosaur", group:"Avialans", period:"Late Jurassic", age:[150,145], measurements:measurements([0.4,0.5], [0.2,0.3], [0.5,1]), diet:"Carnivore", movement:"Moved on two legs and could fly or glide", countries:["Germany"], regions:["Europe"], fact:"Its fossils combine flight feathers with teeth, claws, and a long bony tail.", didYouKnow:"The first feather fossil was found before the first skeleton was recognized.", uncertainty:"Scientists still debate exactly how well Archaeopteryx could fly.", source:NHM }),
    creature({ slug:"sinosauropteryx", name:"Sinosauropteryx", scientificName:"Sinosauropteryx prima", pronunciation:"sigh-noh-sore-OP-ter-iks", meaning:"Chinese lizard wing", type:"Dinosaur", group:"Theropods", period:"Early Cretaceous", age:[125,122], measurements:measurements([1,1.1], [0.3,0.4], [0.5,1]), diet:"Carnivore", movement:"Ran on two legs", countries:["China"], regions:["Asia"], fact:"Fossils preserve a fuzzy coat of simple feathers.", didYouKnow:"Pigment structures helped scientists infer a reddish, ringed tail and countershaded body.", source:NHM }),
    creature({ slug:"therizinosaurus", name:"Therizinosaurus", scientificName:"Therizinosaurus cheloniformis", pronunciation:"thair-ih-ZIN-oh-SORE-us", meaning:"scythe lizard", type:"Dinosaur", group:"Therizinosaurs", period:"Late Cretaceous", age:[70,68], measurements:measurements([9,10], [4,5], [3000,5000]), diet:"Herbivore", movement:"Walked on two legs", countries:["Mongolia"], regions:["Asia"], fact:"Its enormous hand claws could reach about a meter long.", didYouKnow:"Although related to meat-eating theropods, it probably ate mostly plants.", uncertainty:"Only parts of its skeleton are known, so its full size is estimated from relatives.", source:NHM }),
    creature({ slug:"oviraptor", name:"Oviraptor", scientificName:"Oviraptor philoceratops", pronunciation:"OH-vih-RAP-tor", meaning:"egg thief", type:"Dinosaur", group:"Oviraptorosaurs", period:"Late Cretaceous", age:[75,71], measurements:measurements([1.5,2], [0.8,1], [20,40]), diet:"Omnivore", movement:"Walked on two legs", countries:["Mongolia"], regions:["Asia"], fact:"It had feathers, a toothless beak, and a crest on its head.", didYouKnow:"It was accused of stealing eggs, but later finds showed similar dinosaurs brooding their own nests.", uncertainty:"Its exact menu is uncertain and may have included plants, eggs, shellfish, and small animals.", source:NHM }),
    creature({ slug:"giganotosaurus", name:"Giganotosaurus", scientificName:"Giganotosaurus carolinii", pronunciation:"jig-ah-NOT-oh-SORE-us", meaning:"giant southern lizard", type:"Dinosaur", group:"Theropods", period:"Late Cretaceous", age:[99,95], measurements:measurements([12,13], [3.5,4], [6000,8000]), diet:"Carnivore", movement:"Walked on two legs", countries:["Argentina"], regions:["South America"], fact:"It was one of the largest land predators, with a long skull and blade-like teeth.", didYouKnow:"It lived millions of years before Tyrannosaurus rex and on a different continent.", source:NHM }),
    creature({ slug:"patagotitan", name:"Patagotitan", scientificName:"Patagotitan mayorum", pronunciation:"PAT-ah-go-TIE-tan", meaning:"Patagonian titan", type:"Dinosaur", group:"Sauropods", period:"Late Cretaceous", age:[102,95], measurements:measurements([31,37], [6,8], [50000,69000]), diet:"Herbivore", movement:"Walked on four legs", countries:["Argentina"], regions:["South America"], fact:"This titanosaur was among the largest land animals ever discovered.", didYouKnow:"Hundreds of bones from at least six individuals were found at one ranch.", uncertainty:"Its maximum size is debated because no complete skeleton has been found.", source:NHM }),
    creature({ slug:"psittacosaurus", name:"Psittacosaurus", scientificName:"Psittacosaurus mongoliensis", pronunciation:"sit-ACK-oh-SORE-us", meaning:"parrot lizard", type:"Dinosaur", group:"Ceratopsians", period:"Early Cretaceous", age:[126,101], measurements:measurements([1.5,2], [0.6,0.8], [15,25]), diet:"Herbivore", movement:"Usually walked on two legs as an adult", countries:["China","Mongolia","Russia"], regions:["Asia"], fact:"This early horned-dinosaur relative had a strong parrot-like beak but no large horns.", didYouKnow:"Some fossils preserve long bristle-like structures on the tail.", source:NHM }),
    creature({ slug:"edmontosaurus", name:"Edmontosaurus", scientificName:"Edmontosaurus annectens", pronunciation:"ed-MON-toh-SORE-us", meaning:"Edmonton lizard", type:"Dinosaur", group:"Hadrosaurs", period:"Late Cretaceous", age:[73,66], measurements:measurements([9,12], [3,4], [3000,5000]), diet:"Herbivore", movement:"Could move on two or four legs", countries:["Canada","United States"], regions:["North America"], fact:"Rows of replacement teeth formed broad dental batteries for grinding plants.", didYouKnow:"Skin impressions and a soft-tissue head crest have been preserved in rare fossils.", source:NHM }),
    creature({ slug:"maiasaura", name:"Maiasaura", scientificName:"Maiasaura peeblesorum", pronunciation:"MY-ah-SORE-ah", meaning:"good mother lizard", type:"Dinosaur", group:"Hadrosaurs", period:"Late Cretaceous", age:[77,75], measurements:measurements([7,9], [2.5,3], [2500,4500]), diet:"Herbivore", movement:"Could move on two or four legs", countries:["United States"], regions:["North America"], fact:"Nesting grounds show many nests spaced close together in colonies.", didYouKnow:"Tiny hatchlings had weak legs, suggesting adults may have brought food to the nest.", source:NHM }),
    creature({ slug:"utahraptor", name:"Utahraptor", scientificName:"Utahraptor ostrommaysorum", pronunciation:"YOO-tah-RAP-tor", meaning:"Utah thief", type:"Dinosaur", group:"Dromaeosaurs", period:"Early Cretaceous", age:[135,130], measurements:measurements([5,6], [1.5,2], [250,500]), diet:"Carnivore", movement:"Walked and ran on two legs", countries:["United States"], regions:["North America"], fact:"It was much larger and more heavily built than Velociraptor.", didYouKnow:"Its curved toe claw could grow to more than 20 centimeters along the curve.", source:NHM }),
    creature({ slug:"microraptor", name:"Microraptor", scientificName:"Microraptor gui", pronunciation:"MY-kroh-RAP-tor", meaning:"small thief", type:"Dinosaur", group:"Dromaeosaurs", period:"Early Cretaceous", age:[125,120], measurements:measurements([0.7,1], [0.2,0.3], [0.8,1.5]), diet:"Carnivore", movement:"Climbed, glided, and moved on two legs", countries:["China"], regions:["Asia"], fact:"Long flight feathers grew from both its arms and legs, creating four wing-like surfaces.", didYouKnow:"Fossil pigment structures suggest glossy black, iridescent feathers.", uncertainty:"Scientists continue to test how it held its legs and moved through the air.", source:NHM }),

    creature({ slug:"pteranodon", name:"Pteranodon", scientificName:"Pteranodon longiceps", pronunciation:"teh-RAN-oh-don", meaning:"wing without tooth", type:"Pterosaur", group:"Pterosaurs", period:"Late Cretaceous", age:[86,84], measurements:measurements([null,null], [null,null], [20,35]), wingspan:[5.5,7], diet:"Piscivore", movement:"Flew and walked on all four limbs", countries:["United States"], regions:["North America"], fact:"This toothless flying reptile used long wings to soar over an inland sea.", didYouKnow:"The long head crest may have helped with display or steering.", source:SMITHSONIAN }),
    creature({ slug:"quetzalcoatlus", name:"Quetzalcoatlus", scientificName:"Quetzalcoatlus northropi", pronunciation:"ket-sal-koh-AT-lus", meaning:"named for the feathered serpent Quetzalcoatl", type:"Pterosaur", group:"Pterosaurs", period:"Late Cretaceous", age:[68,66], measurements:measurements([null,null], [5,5.5], [180,250]), wingspan:[10,11], diet:"Carnivore", movement:"Flew and walked on all four limbs", countries:["United States"], regions:["North America"], fact:"One of the largest known flying animals, it stood as tall as a giraffe on the ground.", didYouKnow:"It may have stalked small animals on land rather than catching fish like a gull.", uncertainty:"Its maximum wingspan and body mass are estimates based on incomplete remains.", source:SMITHSONIAN }),
    creature({ slug:"dimorphodon", name:"Dimorphodon", scientificName:"Dimorphodon macronyx", pronunciation:"dye-MOR-foh-don", meaning:"two-form tooth", type:"Pterosaur", group:"Pterosaurs", period:"Early Jurassic", age:[195,190], measurements:measurements([1,1], [0.3,0.5], [1.5,2]), wingspan:[1.4,1.7], diet:"Carnivore", movement:"Flew and climbed or walked on all four limbs", countries:["United Kingdom"], regions:["Europe"], fact:"Its large head held two different shapes of teeth, which inspired its name.", didYouKnow:"Pterosaurs were flying reptiles, not dinosaurs or birds.", source:SMITHSONIAN }),
    creature({ slug:"mosasaurus", name:"Mosasaurus", scientificName:"Mosasaurus hoffmannii", pronunciation:"MOH-zah-SORE-us", meaning:"Meuse River lizard", type:"Marine reptile", group:"Mosasaurs", period:"Late Cretaceous", age:[82,66], measurements:measurements([11,15], [null,null], [7000,14000]), diet:"Carnivore", movement:"Swam using flippers and a powerful tail", countries:["Belgium","Morocco","Netherlands","United States"], regions:["Europe","Africa","North America"], fact:"This giant ocean predator was a close relative of modern monitor lizards and snakes.", didYouKnow:"Mosasaurus gave birth to live young instead of laying eggs on land.", source:SMITHSONIAN }),
    creature({ slug:"plesiosaurus", name:"Plesiosaurus", scientificName:"Plesiosaurus dolichodeirus", pronunciation:"PLEE-see-oh-SORE-us", meaning:"near lizard", type:"Marine reptile", group:"Plesiosaurs", period:"Early Jurassic", age:[201,175], measurements:measurements([3,5], [null,null], [100,450]), diet:"Piscivore", movement:"Swam with four powerful flippers", countries:["United Kingdom"], regions:["Europe"], fact:"A small head sat at the end of a long flexible neck, while four flippers powered its body.", didYouKnow:"It could not bend its neck into a swan-like S-shape as old pictures often show.", source:SMITHSONIAN }),
    creature({ slug:"ichthyosaurus", name:"Ichthyosaurus", scientificName:"Ichthyosaurus communis", pronunciation:"ICK-thee-oh-SORE-us", meaning:"fish lizard", type:"Marine reptile", group:"Ichthyosaurs", period:"Early Jurassic", age:[201,182], measurements:measurements([2,3.3], [null,null], [80,250]), diet:"Piscivore", movement:"Swam with flippers and a fish-like tail", countries:["Belgium","Germany","Switzerland","United Kingdom"], regions:["Europe"], fact:"Its streamlined body evolved a dolphin-like shape even though it was a reptile.", didYouKnow:"Exceptional fossils show that ichthyosaurs gave birth to live young tail-first.", source:SMITHSONIAN }),
    creature({ slug:"liopleurodon", name:"Liopleurodon", scientificName:"Liopleurodon ferox", pronunciation:"LY-oh-PLOOR-oh-don", meaning:"smooth-sided tooth", type:"Marine reptile", group:"Pliosaurs", period:"Middle to Late Jurassic", age:[166,155], measurements:measurements([5,7], [null,null], [1000,2500]), diet:"Carnivore", movement:"Swam with four powerful flippers", countries:["France","Germany","United Kingdom"], regions:["Europe"], fact:"Its huge head and strong jaws belonged to a short-necked kind of plesiosaur called a pliosaur.", didYouKnow:"Television once made it look far larger than fossil evidence supports.", uncertainty:"No complete skeleton is known, so maximum size estimates vary.", source:SMITHSONIAN }),
    creature({ slug:"dimetrodon", name:"Dimetrodon", scientificName:"Dimetrodon grandis", pronunciation:"dye-MEE-troh-don", meaning:"two measures of teeth", type:"Synapsid", group:"Early synapsids", period:"Early Permian", age:[295,272], measurements:measurements([3,4.5], [1.5,2], [100,250]), diet:"Carnivore", movement:"Walked on four sprawling legs", countries:["Germany","United States"], regions:["North America","Europe"], fact:"Dimetrodon lived before the first dinosaurs and was more closely related to mammals than to reptiles.", didYouKnow:"Its tall back sail was supported by greatly lengthened spines from its vertebrae.", source:SMITHSONIAN }),
    creature({ slug:"deinosuchus", name:"Deinosuchus", scientificName:"Deinosuchus hatcheri", pronunciation:"DYE-noh-SOO-kus", meaning:"terrible crocodile", type:"Crocodyliform", group:"Crocodyliforms", period:"Late Cretaceous", age:[82,73], measurements:measurements([8,10.5], [1.2,1.5], [2500,5000]), diet:"Carnivore", movement:"Swam and walked on four legs", countries:["Mexico","United States"], regions:["North America"], fact:"This enormous relative of alligators waited in waterways where dinosaurs came to drink.", didYouKnow:"Bite marks on dinosaur bones show that Deinosuchus sometimes attacked very large prey.", uncertainty:"Its full length is estimated because complete skeletons are rare.", source:SMITHSONIAN })
  ];
})();
