(function () {
  const WIKI = "https://en.wikipedia.org/wiki/";
  const measurements = (length, height, weightKg) => ({ length, height, weightKg });
  const truck = (entry) => Object.assign({
    alternateName: "",
    variation: "Sizes change from one model to another, so these are typical examples.",
    image: null
  }, entry);

  window.TRUCKS = [
    truck({ slug:"excavator", name:"Excavator", alternateName:"Digger", category:"Construction", job:"Digs deep holes and moves soil or rocks.", settings:["building sites","road projects","quarries"], measurements:measurements([6,11],[2.5,4],[7000,45000]), power:"A diesel engine powers strong hydraulic pumps.", equipment:"Boom, stick, bucket, tracks, and a spinning upper cab", how:"Hydraulic fluid pushes giant metal arms. The cab can turn all the way around without moving the tracks.", size:"A large one can weigh as much as six elephants.", coolFact:"Some excavators trade their bucket for a giant hammer, claw, drill, or magnet.", source:WIKI+"Excavator" }),
    truck({ slug:"bulldozer", name:"Bulldozer", category:"Construction", job:"Pushes dirt, sand, rubble, and snow.", settings:["building sites","mines","farms"], measurements:measurements([4,9],[2.5,4.5],[8000,50000]), power:"A powerful diesel engine turns wide metal tracks.", equipment:"A huge front blade and a rear ripper tooth", how:"Its tracks spread the weight over the ground. The blade shoves material while the ripper breaks hard earth.", size:"Its blade can be wider than a family car is long.", coolFact:"The tracks help a bulldozer crawl over soft mud where wheels might sink.", source:WIKI+"Bulldozer" }),
    truck({ slug:"dump-truck", name:"Dump Truck", category:"Construction", job:"Carries loose loads such as dirt, gravel, and broken rock.", settings:["building sites","roads","mines"], measurements:measurements([6,10],[2.5,4],[10000,40000]), power:"A diesel engine drives the wheels and a hydraulic ram lifts the bed.", equipment:"A strong tipping bed and a hinged tailgate", how:"The truck carries its load with the bed flat. At the delivery spot, the bed tilts up and the load slides out.", size:"A road dump truck may carry about ten small-car loads of dirt.", coolFact:"Enormous mine dump trucks are so big that drivers climb stairs to reach the cab.", source:WIKI+"Dump_truck" }),
    truck({ slug:"front-end-loader", name:"Front-end Loader", alternateName:"Wheel loader", category:"Construction", job:"Scoops and carries piles of loose material.", settings:["building sites","quarries","farms"], measurements:measurements([5,10],[2.5,4],[7000,35000]), power:"A diesel engine drives four big wheels and hydraulic arms.", equipment:"A wide bucket on two lifting arms", how:"The bucket slides into a pile, curls upward to hold the load, then lifts high enough to fill a truck.", size:"A big loader's bucket can hold a whole backyard sandbox.", coolFact:"Its middle bends like an elbow so the machine can turn in tight spaces.", source:WIKI+"Loader_(equipment)" }),
    truck({ slug:"backhoe", name:"Backhoe", alternateName:"Backhoe loader", category:"Construction", job:"Digs with one end and scoops with the other.", settings:["building sites","farms","utility repairs"], measurements:measurements([6,8],[2.5,3.5],[7000,11000]), power:"A diesel engine powers wheels and hydraulics.", equipment:"A loader bucket in front and a digging arm in back", how:"The operator turns the seat to choose a tool. Folding support legs keep the machine steady while it digs.", size:"It is about as long as two beds placed end to end.", coolFact:"A backhoe is two useful machines joined together.", source:WIKI+"Backhoe_loader" }),
    truck({ slug:"skid-steer-loader", name:"Skid-steer Loader", alternateName:"Skid steer", category:"Construction", job:"Lifts, pushes, digs, and cleans in small spaces.", settings:["building sites","barns","landscaping jobs"], measurements:measurements([2.5,3.8],[1.8,2.2],[1200,4500]), power:"An engine powers wheels or tracks and hydraulic tool arms.", equipment:"Lift arms with quick-change attachments", how:"The wheels on each side can move at different speeds. That lets the loader spin almost in place.", size:"Many skid steers are shorter than a pickup truck.", coolFact:"It can swap its bucket for forks, a snow blower, a broom, or even a tree spade.", source:WIKI+"Skid-steer_loader" }),
    truck({ slug:"cement-mixer", name:"Cement Mixer", alternateName:"Concrete mixer truck", category:"Construction", job:"Carries freshly mixed concrete to a building site.", settings:["roads","homes","big buildings"], measurements:measurements([7,10],[3,4],[12000,30000]), power:"The truck engine drives the wheels; hydraulics turn the drum.", equipment:"A striped spinning drum and a pouring chute", how:"Spiral blades inside the turning drum keep concrete mixed. Reverse the spin and the concrete moves down the chute.", size:"A mixer can carry enough concrete for a small driveway.", coolFact:"The drum turns slowly while the truck travels so the concrete stays ready to pour.", source:WIKI+"Concrete_mixer" }),
    truck({ slug:"concrete-pump-truck", name:"Concrete Pump Truck", category:"Construction", job:"Sends wet concrete high up or far across a building site.", settings:["bridges","tall buildings","large foundations"], measurements:measurements([9,14],[3.5,4],[25000,50000]), power:"A diesel engine powers a high-pressure pump and hydraulic boom.", equipment:"A folding boom with a long concrete hose", how:"Pistons push concrete through a pipe. The unfolding boom places the hose where a mixer truck cannot drive.", size:"Some booms can reach higher than a ten-story building.", coolFact:"The boom folds into a compact zigzag for the drive to work.", source:WIKI+"Concrete_pump" }),
    truck({ slug:"mobile-crane", name:"Mobile Crane", alternateName:"Truck crane", category:"Construction", job:"Lifts very heavy things high into the air.", settings:["building sites","bridges","factories"], measurements:measurements([10,18],[3.5,4],[30000,96000]), power:"A large engine powers the wheels, winch, and hydraulic boom.", equipment:"Telescoping boom, steel cable, hook, and outriggers", how:"Outriggers spread wide to make a steady base. A winch winds cable to raise and lower the hook.", size:"A large crane can lift several school buses at once.", coolFact:"Its boom slides out in sections like a giant telescope.", source:WIKI+"Mobile_crane" }),
    truck({ slug:"asphalt-paver", name:"Asphalt Paver", alternateName:"Road paver", category:"Construction", job:"Lays a smooth ribbon of hot asphalt for a new road.", settings:["streets","highways","airport runways"], measurements:measurements([5,8],[2.5,3.5],[8000,22000]), power:"A diesel engine moves tracks or wheels and runs conveyors.", equipment:"Front hopper, hidden conveyor, and wide rear screed", how:"A dump truck fills the hopper. Conveyors move asphalt backward, and the screed spreads and smooths it.", size:"Its paving strip can be wider than two cars side by side.", coolFact:"The screed is heated so sticky asphalt will glide beneath it.", source:WIKI+"Paver_(vehicle)" }),

    truck({ slug:"fire-engine", name:"Fire Engine", alternateName:"Pumper", category:"Emergency", job:"Brings firefighters, hoses, tools, and water to help at emergencies.", settings:["towns","cities","country roads"], measurements:measurements([8,11],[3,3.7],[13000,23000]), power:"A diesel engine drives the truck and a powerful water pump.", equipment:"Water tank, pump, hoses, ladders, and flashing lights", how:"The pump pulls water from the truck tank or a hydrant and pushes it through long hoses.", size:"Its water tank may hold more than ten bathtubs of water.", coolFact:"Fire engines carry many hose sizes because each job needs a different flow of water.", source:WIKI+"Fire_engine" }),
    truck({ slug:"ladder-truck", name:"Ladder Truck", alternateName:"Aerial ladder truck", category:"Emergency", job:"Raises firefighters and equipment high above the street.", settings:["cities","airports","large buildings"], measurements:measurements([10,15],[3.2,4],[20000,36000]), power:"A diesel engine and hydraulic system raise and turn the ladder.", equipment:"A long telescoping ladder, turntable, and stabilizing outriggers", how:"The truck plants its outriggers, turns the ladder base, then slides ladder sections outward.", size:"A 30-meter ladder can reach about as high as a ten-story building.", coolFact:"Some ladder trucks have a second driver at the back to help steer around tight corners.", source:WIKI+"Turntable_ladder" }),
    truck({ slug:"ambulance", name:"Ambulance", category:"Emergency", job:"Brings a medical team and equipment to people who need help.", settings:["neighborhoods","highways","events"], measurements:measurements([5.5,7],[2.5,3],[3500,6500]), power:"A gasoline or diesel engine drives the vehicle and powers medical equipment.", equipment:"Stretcher, medical supplies, bright lights, and siren", how:"The driver makes a safe path while trained helpers care for the patient in the roomy back.", size:"It is often about as long as a large pickup truck.", coolFact:"Some ambulances are boats, helicopters, motorcycles, or even snow vehicles.", source:WIKI+"Ambulance" }),
    truck({ slug:"police-car", name:"Police Car", alternateName:"Patrol car", category:"Emergency", job:"Helps police officers travel, carry gear, and keep roads safe.", settings:["streets","highways","parks"], measurements:measurements([4.5,5.5],[1.4,2],[1700,3000]), power:"A gasoline, hybrid, or electric motor drives the wheels.", equipment:"Radio, lights, siren, safety gear, and storage", how:"A radio shares calls with the officer. Bright lights and a siren ask other drivers to make room.", size:"It is close in size to an ordinary family car or SUV.", coolFact:"Police vehicles can be cars, trucks, motorcycles, bicycles, boats, and horses.", source:WIKI+"Police_car" }),
    truck({ slug:"heavy-rescue-truck", name:"Heavy Rescue Truck", category:"Emergency", job:"Carries a big toolbox for difficult rescues.", settings:["cities","highways","industrial sites"], measurements:measurements([8,12],[3,4],[14000,27000]), power:"A diesel engine drives the truck and may power generators and tools.", equipment:"Cutting tools, ropes, air tanks, lights, and a generator", how:"Roll-up doors open to organized tool compartments so a rescue team can quickly find exactly what it needs.", size:"It can be as long as a city bus.", coolFact:"Many rescue trucks are rolling workshops with power, air, and bright scene lights.", source:WIKI+"Rescue_vehicle" }),
    truck({ slug:"airport-crash-tender", name:"Airport Crash Tender", alternateName:"Airport fire truck", category:"Emergency", job:"Carries water and firefighting foam quickly across an airport.", settings:["airports","airfields"], measurements:measurements([10,13],[3.5,4.2],[30000,50000]), power:"Huge diesel engines drive all-wheel systems and powerful pumps.", equipment:"Roof water cannon, big tanks, giant tires, and all-wheel drive", how:"It races safely across pavement or grass. A roof cannon can spray while the truck is still moving.", size:"A large one can weigh about as much as thirty cars.", coolFact:"Some can speed from a stop to 80 km/h in less than half a minute.", source:WIKI+"Airport_crash_tender" }),

    truck({ slug:"garbage-truck", name:"Garbage Truck", alternateName:"Refuse truck", category:"City Helpers", job:"Collects waste and carries it away from homes and businesses.", settings:["neighborhoods","cities","transfer stations"], measurements:measurements([8,11],[3,4],[14000,30000]), power:"A diesel, natural-gas, or electric motor moves the truck and hydraulic lifters.", equipment:"Bin lifter, packing blade, and sealed body", how:"A lifting arm empties a bin. Inside, a strong blade presses the load so the truck can carry more.", size:"It may visit hundreds of homes before it is full.", coolFact:"Some have steering wheels on both sides so drivers can work safely beside the curb.", source:WIKI+"Garbage_truck" }),
    truck({ slug:"street-sweeper", name:"Street Sweeper", category:"City Helpers", job:"Brushes dirt, leaves, and litter from streets.", settings:["city streets","parking lots","airport roads"], measurements:measurements([4,8],[2.5,3.5],[5000,15000]), power:"An engine or electric motor moves the truck and spins brushes and fans.", equipment:"Round gutter brushes, water sprayers, vacuum, and dirt hopper", how:"Water keeps dust down, brushes flick dirt inward, and a strong airflow carries it into a hopper.", size:"Its side brushes can reach underneath the edge of parked cars.", coolFact:"The big round brushes look like spinning mustaches.", source:WIKI+"Street_sweeper" }),
    truck({ slug:"snowplow", name:"Snowplow", category:"City Helpers", job:"Pushes snow off roads so people can travel safely.", settings:["snowy streets","highways","airport runways"], measurements:measurements([6,12],[3,4],[10000,30000]), power:"A diesel engine drives the truck and hydraulics angle the plow.", equipment:"Front plow, salt spreader, and sometimes a side wing", how:"The angled blade rolls snow toward the roadside. A rear spreader may drop salt or grit for better grip.", size:"With its wing open, a highway plow can clear more than one lane.", coolFact:"Some airports use giant plows in teams to clear a runway quickly.", source:WIKI+"Snowplow" }),
    truck({ slug:"tow-truck", name:"Tow Truck", alternateName:"Wrecker", category:"City Helpers", job:"Moves vehicles that cannot drive by themselves.", settings:["streets","highways","repair shops"], measurements:measurements([5.5,10],[2.2,3.5],[5000,25000]), power:"An engine drives the truck and powers hydraulic lifts and winches.", equipment:"Winch cable, wheel lift, boom, or tilting flatbed", how:"A winch pulls a vehicle onto a flatbed, or a wheel lift raises one end so the other wheels can roll.", size:"Heavy wreckers can tow buses and tractor-trailers.", coolFact:"The first tow truck was built in 1916 by a mechanic who needed an easier way to rescue cars.", source:WIKI+"Tow_truck" }),
    truck({ slug:"bucket-truck", name:"Bucket Truck", alternateName:"Cherry picker", category:"City Helpers", job:"Lifts a worker safely to places high above the ground.", settings:["power lines","streetlights","tree work"], measurements:measurements([6,11],[3,4],[7000,23000]), power:"A truck engine or battery powers hydraulic lifting arms.", equipment:"Insulated boom, work bucket, controls, and outriggers", how:"The folding boom raises and swings the bucket. Outriggers keep the truck steady while someone works aloft.", size:"Some buckets can reach higher than a six-story building.", coolFact:"Special insulated booms help utility crews work near electrical wires.", source:WIKI+"Aerial_work_platform" }),
    truck({ slug:"school-bus", name:"School Bus", category:"City Helpers", job:"Carries children safely to and from school.", settings:["neighborhoods","country roads","school trips"], measurements:measurements([6,12],[2.8,3.4],[7000,16000]), power:"A diesel, gasoline, propane, or electric motor drives the bus.", equipment:"Flashing lights, stop arm, tall seats, and many mirrors", how:"The driver uses mirrors to watch all around the bus. Red lights and the stop arm tell traffic to wait.", size:"A full-size bus can carry about as many children as three classrooms.", coolFact:"School-bus yellow was chosen because black letters are easy to see on it, even early in the morning.", source:WIKI+"School_bus" }),

    truck({ slug:"semi-truck", name:"Semi-truck", alternateName:"Tractor-trailer", category:"Big Haulers", job:"Pulls a long trailer full of goods over great distances.", settings:["highways","warehouses","shipping yards"], measurements:measurements([16,23],[3.5,4.1],[15000,36000]), power:"A large diesel or electric motor drives the tractor's wheels.", equipment:"Tractor cab, fifth-wheel hitch, air brakes, and trailer", how:"The tractor clips beneath the trailer at a strong round hitch. Air lines connect the trailer brakes.", size:"A common trailer is about as long as four family cars.", coolFact:"The trailer is called a semi because it has wheels at the back but rests on the tractor at the front.", source:WIKI+"Semi-trailer_truck" }),
    truck({ slug:"tanker-truck", name:"Tanker Truck", category:"Big Haulers", job:"Carries liquids or gases inside a strong tank.", settings:["highways","farms","airports","fuel stations"], measurements:measurements([8,18],[3,4],[12000,36000]), power:"A diesel engine drives the truck; pumps may load and unload the tank.", equipment:"Rounded tank, hoses, valves, and inner baffles", how:"Pumps move liquid through hoses. Walls called baffles slow the sloshing so the truck stays easier to control.", size:"A highway fuel tanker may hold enough liquid to fill more than 300 car fuel tanks.", coolFact:"Some tankers carry milk, water, flour, chocolate, or even orange juice.", source:WIKI+"Tank_truck" }),
    truck({ slug:"car-carrier", name:"Car Carrier", alternateName:"Auto transporter", category:"Big Haulers", job:"Moves several cars at the same time.", settings:["highways","car factories","dealerships"], measurements:measurements([17,23],[4,4.2],[18000,36000]), power:"A diesel tractor pulls the trailer; hydraulics move the loading decks.", equipment:"Two-level trailer, folding ramps, and wheel straps", how:"Ramps and decks tilt so cars can drive into place. Strong straps hold every wheel still for the trip.", size:"A large carrier can hold about eight or nine cars.", coolFact:"Its decks fit together like a moving metal puzzle.", source:WIKI+"Car_carrier_trailer" }),
    truck({ slug:"flatbed-truck", name:"Flatbed Truck", category:"Big Haulers", job:"Carries large loads that do not fit inside a box trailer.", settings:["highways","building sites","farms"], measurements:measurements([7,20],[2.5,4],[10000,36000]), power:"A diesel engine drives the truck or tractor.", equipment:"Open flat deck, chains, straps, and sometimes a small crane", how:"A crane or forklift places cargo on the open deck. Straps and chains stop it from sliding or tipping.", size:"A long flatbed can carry giant pipes, lumber, or another machine.", coolFact:"Because there are no walls, a flatbed can be loaded from either side or from above.", source:WIKI+"Flatbed_truck" }),
    truck({ slug:"logging-truck", name:"Logging Truck", category:"Big Haulers", job:"Carries cut tree trunks from forests to mills.", settings:["forest roads","highways","sawmills"], measurements:measurements([12,25],[3.5,4.2],[20000,60000]), power:"A heavy diesel engine pulls the load over steep roads.", equipment:"Strong stakes, chains, trailer, and sometimes a loading crane", how:"Logs rest between tall stakes and are secured with chains. Some trailers telescope to fit different log lengths.", size:"Its load can be longer than a bowling lane.", coolFact:"Some empty logging trailers can ride piggyback on the truck for the trip back to the forest.", source:WIKI+"Logging_truck" }),
    truck({ slug:"mining-haul-truck", name:"Mining Haul Truck", alternateName:"Off-highway dump truck", category:"Big Haulers", job:"Moves enormous loads of rock around a mine.", settings:["open-pit mines","huge quarries"], measurements:measurements([10,21],[5,8],[100000,600000]), power:"A giant diesel engine often generates electricity for wheel motors.", equipment:"Rock body, huge tires, ladders, and powerful brakes", how:"A loader fills the bed with rock. At the dump point, hydraulic cylinders lift the entire bed high into the air.", size:"The biggest ones can carry more than 300 family cars' worth of weight.", coolFact:"One tire can be taller than a two-story room.", source:WIKI+"Haul_truck" }),

    truck({ slug:"farm-tractor", name:"Farm Tractor", category:"Farm & Worksite", job:"Pulls and powers tools that help farmers grow food.", settings:["farms","orchards","fields"], measurements:measurements([3,6],[2,3.5],[1500,14000]), power:"A diesel or electric motor drives big rear wheels or tracks.", equipment:"Hitch, power take-off shaft, hydraulic connectors, and chunky tires", how:"The hitch pulls an implement. A spinning power shaft and hydraulic hoses can make the tool work.", size:"A large tractor tire can be taller than a grown-up.", coolFact:"A tractor may plant, mow, plow, spray, bale, or pull—but it changes tools for each job.", source:WIKI+"Tractor" }),
    truck({ slug:"combine-harvester", name:"Combine Harvester", alternateName:"Combine", category:"Farm & Worksite", job:"Cuts a crop, separates the grain, and cleans it—all in one trip.", settings:["wheat fields","corn fields","farms"], measurements:measurements([7,12],[3.5,4.5],[10000,25000]), power:"A diesel engine drives wheels and many belts, fans, and cutters.", equipment:"Wide header, threshing drum, sieves, grain tank, and unloading auger", how:"The header gathers plants. Inside, the machine shakes grain free and blows away light bits of stalk.", size:"Its front header can be wider than a tennis court is across.", coolFact:"The name combine comes from combining several harvesting jobs in one machine.", source:WIKI+"Combine_harvester" }),
    truck({ slug:"forklift", name:"Forklift", category:"Farm & Worksite", job:"Lifts heavy boxes and pallets and stacks them neatly.", settings:["warehouses","factories","shipping yards"], measurements:measurements([2.5,5],[2,3],[2000,9000]), power:"A battery, propane engine, or diesel engine powers the wheels and hydraulics.", equipment:"Two steel forks, lifting mast, chains, and a rear counterweight", how:"The forks slide under a pallet. Hydraulic cylinders raise the mast while the heavy back keeps the truck balanced.", size:"A common forklift can lift about the weight of a rhinoceros.", coolFact:"Forklifts steer with their back wheels, helping them turn through narrow aisles.", source:WIKI+"Forklift" }),
    truck({ slug:"feller-buncher", name:"Feller Buncher", category:"Farm & Worksite", job:"Cuts trees and gathers them into tidy bunches.", settings:["managed forests","tree farms"], measurements:measurements([6,9],[3,4],[18000,40000]), power:"A diesel engine powers tracks, hydraulic arms, and the cutting head.", equipment:"Grabbing arms and a cutting saw or shear", how:"The head grips a tree, cuts it near the ground, then holds it while the machine collects more trees.", size:"Its cutting head can hold several tree trunks at once.", coolFact:"Its name says exactly what it does: it fells trees and bunches them together.", source:WIKI+"Feller_buncher" }),

    truck({ slug:"monster-truck", name:"Monster Truck", category:"Extraordinary", job:"Performs jumps, wheelies, races, and car-crushing stunts.", settings:["stadiums","arenas","outdoor shows"], measurements:measurements([5,6],[3,4],[4500,6000]), power:"A supercharged engine sends huge power to all four wheels.", equipment:"Giant tires, strong roll cage, long-travel suspension, and rear steering", how:"Soft suspension soaks up hard landings. Front and rear steering help the truck turn despite its enormous tires.", size:"Each tire can be about as tall as a five-year-old standing on another five-year-old's shoulders.", coolFact:"A monster-truck tire may weigh more than 350 kilograms before it even touches the dirt.", source:WIKI+"Monster_truck" }),
    truck({ slug:"ice-cream-truck", name:"Ice Cream Truck", alternateName:"Ice cream van", category:"Extraordinary", job:"Brings frozen treats to neighborhoods and events.", settings:["neighborhoods","parks","festivals"], measurements:measurements([4.5,7],[2.5,3.2],[3000,6000]), power:"A gasoline, diesel, or electric motor drives it; freezers keep treats cold.", equipment:"Freezer, serving window, colorful signs, and music speaker", how:"A cold freezer holds the treats while the truck travels. The driver parks safely and serves through a side window.", size:"It is usually about the size of a delivery van.", coolFact:"Horse-drawn ice cream wagons visited streets before motor trucks became common.", source:WIKI+"Ice_cream_van" }),
    truck({ slug:"aircraft-deicer", name:"Aircraft Deicer", alternateName:"Deicing truck", category:"Extraordinary", job:"Sprays warm deicing fluid to clear frost, snow, and ice from airplanes.", settings:["airports","cold-weather airfields"], measurements:measurements([8,13],[3.5,5],[18000,35000]), power:"A diesel engine moves the truck and runs pumps, heaters, and the boom.", equipment:"Heated fluid tanks, lifting boom, operator cab, and spray nozzle", how:"The boom raises an operator near the aircraft. Warm fluid sprays across wings and tail before takeoff.", size:"Its boom may lift the small cab higher than an airplane's tail.", coolFact:"The deicing fluid is often dyed bright orange so workers can see where it has been sprayed.", source:WIKI+"Deicing_fluid" }),
    truck({ slug:"crawler-transporter", name:"NASA Crawler-Transporter", alternateName:"The Crawler", category:"Extraordinary", job:"Carries giant rockets and their launch platform to the launchpad.", settings:["Kennedy Space Center in Florida"], measurements:measurements([40,40],[6,8],[2700000,3000000]), power:"Two huge diesel engines generate electricity for sixteen traction motors.", equipment:"Eight giant tracks, leveling system, control rooms, and lifting points", how:"The crawler creeps along a special rock road. Its leveling system keeps the rocket upright even on a slope.", size:"Its top deck is almost as big as a baseball infield.", coolFact:"When it carries a rocket, it moves more slowly than most people walk.", variation:"NASA built two crawlers. Upgrades have changed their exact weight and carrying power over time.", source:"https://www.nasa.gov/kennedy/crawler-transporters/" })
  ];
})();
