(function () {
  const WIKI = "https://en.wikipedia.org/wiki/";
  const NHTSA = "https://www.nhtsa.gov/ratings";
  const IIHS = "https://www.iihs.org/ratings";
  const makers = [
    ["mazda", "Mazda", "MZ", "#e84d3c", "Mazda mixes everyday usefulness with a playful, zoom-zoom spirit."],
    ["honda", "Honda", "H", "#e53b36", "Honda is famous for clever engineering, efficient engines, and cars built for daily life."],
    ["toyota", "Toyota", "T", "#e7353b", "Toyota makes everything from family favorites to trail trucks and sports cars."],
    ["ford", "Ford", "F", "#1773b9", "Ford helped put the world on wheels and still builds some of America's best-known vehicles."],
    ["chevrolet", "Chevrolet", "CH", "#f1b82d", "Chevrolet's bowtie has appeared on work trucks, family cars, and racing legends."],
    ["nissan", "Nissan", "N", "#cf3b47", "Nissan's garage stretches from practical commuters to famous Z sports cars."],
    ["volkswagen", "Volkswagen", "VW", "#1f78b4", "Volkswagen has created friendly people's cars, hot hatchbacks, vans, and electric vehicles."],
    ["bmw", "BMW", "BMW", "#2586c7", "BMW is known for precise driving machines, from tiny bubble cars to quick sedans and SUVs."],
    ["mercedes-benz", "Mercedes-Benz", "MB", "#555f69", "Mercedes-Benz has spent more than a century inventing luxury, safety, and speed."],
    ["porsche", "Porsche", "P", "#d29a21", "Porsche turns racing ideas into distinctive sports cars—and some very speedy family vehicles."],
    ["subaru", "Subaru", "SUB", "#3168b2", "Subaru is loved for all-wheel drive, boxer engines, and ready-for-adventure cars."],
    ["jeep", "Jeep", "J", "#e27a2d", "Jeep grew from tough military machines into a whole family of trail-ready vehicles."]
  ];
  window.CAR_MANUFACTURERS = makers.map(([slug, name, initials, color, blurb]) => ({ slug, name, initials, color, blurb }));

  const official = {
    mazda:"https://www.mazdausa.com/vehicles", honda:"https://automobiles.honda.com/", toyota:"https://www.toyota.com/all-vehicles/", ford:"https://www.ford.com/new-cars/", chevrolet:"https://www.chevrolet.com/", nissan:"https://www.nissanusa.com/vehicles/new.html", volkswagen:"https://www.vw.com/en/models.html", bmw:"https://www.bmwusa.com/all-bmws.html", "mercedes-benz":"https://www.mbusa.com/en/all-vehicles", porsche:"https://www.porsche.com/usa/models/", subaru:"https://www.subaru.com/vehicles/all-vehicles.html", jeep:"https://www.jeep.com/"
  };
  const safe = {
    mazda:"Includes Mazda i-Activsense driver-assistance features; crash results depend on build date and trim.",
    honda:"Includes the Honda Sensing driver-assistance suite; check the exact body style in official crash tests.",
    toyota:"Includes Toyota Safety Sense; crash-test results can differ by drivetrain and body style.",
    ford:"Includes Ford Co-Pilot360 features; official ratings apply only to the tested configuration.",
    chevrolet:"Includes Chevy Safety Assist features; cab, body, and drivetrain can change a vehicle's rating.",
    nissan:"Includes Nissan Safety Shield 360 features; check official results for the exact configuration.",
    volkswagen:"Includes automatic emergency braking and other IQ.DRIVE features; ratings vary by version.",
    bmw:"Offers modern active-safety and driver-assistance systems; ratings vary by options and body style.",
    "mercedes-benz":"Offers modern active braking and driver-assistance systems; ratings vary by configuration.",
    porsche:"Uses modern airbags, stability control, and available driver aids; not every low-volume sports car is crash-rated.",
    subaru:"Includes EyeSight driver assistance on most versions; transmission and trim can affect availability.",
    jeep:"Includes modern airbags and available active-safety aids; ratings vary by doors, body, and drivetrain."
  };
  const currentSources = (make) => [{ label:"Manufacturer specifications", url:official[make] }, { label:"NHTSA ratings", url:NHTSA }, { label:"IIHS ratings", url:IIHS }];
  const historySources = (title) => [{ label:"Model history", url:WIKI + encodeURIComponent(title).replace(/%20/g, "_") }];
  const C = (make, id, name, year, trim, type, seats, interior, size, power, hp, drive, topSpeed, acceleration, fuel, coolFact, wikiTitle) => ({ slug:`${make}-${id}`, make, name, era:"current", year, trim, type, seats, interior, size, power, horsepower:hp, drivetrain:drive, topSpeed, acceleration, fuel, safety:safe[make], coolFact, wikiTitle, sources:currentSources(make) });
  const H = (make, id, name, year, trim, type, seats, interior, size, power, hp, drive, topSpeed, acceleration, fuel, safety, coolFact, wikiTitle) => ({ slug:`${make}-${id}`, make, name, era:"historic", year, trim, type, seats, interior, size, power, horsepower:hp, drivetrain:drive, topSpeed, acceleration, fuel, safety:`Modern crash-rating programs did not test this car. ${safety}`, coolFact, wikiTitle, sources:historySources(wikiTitle) });

  window.CARS = [
    C("mazda","mazda3","Mazda3","2025","2.5 S hatchback","Compact hatchback","5","20.1 cu ft cargo behind the rear seats","176 in long × 70.7 in wide","2.5-liter four-cylinder","191 hp","Front-wheel drive","About 130 mph (estimated)","About 7.3 seconds","Regular gasoline","Its curving body panels are designed to reflect light like a moving sculpture.","Mazda3"),
    C("mazda","cx-30","CX-30","2025","2.5 S","Subcompact SUV","5","20.2 cu ft cargo behind the rear seats","173 in long × 70.7 in wide","2.5-liter four-cylinder","191 hp","All-wheel drive","About 126 mph (estimated)","About 7.6 seconds","Regular gasoline","The CX-30 is shorter than the Mazda3 sedan but has more ground clearance.","Mazda_CX-30"),
    C("mazda","cx-5","CX-5","2025","2.5 S Select","Compact SUV","5","29.1 cu ft cargo behind the rear seats","180.1 in long × 72.6 in wide","2.5-liter four-cylinder","187 hp","All-wheel drive","About 130 mph (estimated)","About 8.5 seconds","Regular gasoline","Every current CX-5 sold in the U.S. sends power to all four wheels.","Mazda_CX-5"),
    C("mazda","mx-5-miata","MX-5 Miata","2025","Sport soft top","Roadster","2","4.6 cu ft trunk","154.1 in long × 68.3 in wide","2.0-liter four-cylinder","181 hp","Rear-wheel drive","About 135 mph","About 5.7 seconds","Premium gasoline recommended","Its manual fabric roof can be opened from the driver's seat with one hand.","Mazda_MX-5"),
    H("mazda","mazda6","Mazda6","2021","Touring","Midsize sedan","5","14.7 cu ft trunk","192.7 in long × 72.4 in wide","2.5-liter four-cylinder","187 hp","Front-wheel drive","About 130 mph","About 7.9 seconds","Gasoline","Later versions had airbags, stability control, and automatic emergency braking.","The Mazda6 name was used across three generations in North America.","Mazda6"),
    H("mazda","rx-7","RX-7","1993","Touring (FD)","Sports coupe","2+2","Tiny rear hatch area","168.5 in long × 68.9 in wide","1.3-liter twin-turbo rotary","255 hp","Rear-wheel drive","155 mph","About 5.0 seconds","Premium gasoline","It predates modern ratings and has far fewer crash protections than a new car.","Its rotary engine has spinning triangular rotors instead of ordinary pistons.","Mazda_RX-7"),
    H("mazda","rx-8","RX-8","2004","Sport","Four-door sports coupe","4","7.6 cu ft trunk","174.3 in long × 69.7 in wide","1.3-liter rotary","238 hp","Rear-wheel drive","About 145 mph","About 6.4 seconds","Premium gasoline","It included front and side airbags, but its ratings cannot be compared directly with today's tests.","Its small rear doors hinge backward, making the back seats easier to reach.","Mazda_RX-8"),
    H("mazda","323-gtx","323 GTX","1988","GTX","Turbo hatchback","5","Compact hatchback cargo area","161.8 in long × 64.8 in wide","1.6-liter turbo four-cylinder","132 hp","All-wheel drive","About 125 mph","About 8.5 seconds","Gasoline","Safety equipment was basic by modern standards and electronic stability control did not exist.","Mazda built it as a tiny road-going cousin of its rally cars.","Mazda_Familia"),

    C("honda","civic","Civic","2025","Sport sedan","Compact sedan","5","14.8 cu ft trunk","184.8 in long × 70.9 in wide","2.0-liter four-cylinder","150 hp","Front-wheel drive","About 126 mph (estimated)","About 8.8 seconds","Regular gasoline","The Civic has been sold through eleven generations since 1972.","Honda_Civic"),
    C("honda","accord","Accord","2025","SE","Midsize sedan","5","16.7 cu ft trunk","195.7 in long × 73.3 in wide","1.5-liter turbo four-cylinder","192 hp","Front-wheel drive","About 116 mph (limited)","About 7.3 seconds","Regular gasoline","The Accord's trunk is larger than those in many similarly sized sedans.","Honda_Accord"),
    C("honda","cr-v","CR-V","2025","EX","Compact SUV","5","39.3 cu ft cargo behind rear seats","184.8 in long × 73.5 in wide","1.5-liter turbo four-cylinder","190 hp","Front-wheel drive","About 115 mph (estimated)","About 8.1 seconds","Regular gasoline","Its rear doors open unusually wide to make loading people and gear easier.","Honda_CR-V"),
    C("honda","pilot","Pilot","2025","EX-L","Midsize SUV","8","18.6 cu ft behind the third row","199.9 in long × 78.5 in wide","3.5-liter V6","285 hp","Front-wheel drive","About 112 mph (limited)","About 6.9 seconds","Regular gasoline","A removable middle seat can turn its second row from a bench into two captain's chairs.","Honda_Pilot"),
    H("honda","s2000","S2000","2008","AP2","Roadster","2","5.0 cu ft trunk","162.2 in long × 68.9 in wide","2.2-liter four-cylinder","237 hp","Rear-wheel drive","About 150 mph","About 5.5 seconds","Premium gasoline","It had airbags and stability control, but today's crash tests use different standards.","Its engine could spin to 8,000 rpm—very high for a road car.","Honda_S2000"),
    H("honda","crx","CRX","1991","Si","Compact hatchback","2","Large hatch area for its tiny size","148.5 in long × 65.9 in wide","1.6-liter four-cylinder","105 hp","Front-wheel drive","About 120 mph","About 8.5 seconds","Gasoline","It was built before modern side-impact and small-overlap crash testing.","The featherweight CRX Si weighed roughly half as much as many modern SUVs.","Honda_CR-X"),
    H("honda","element","Element","2008","EX AWD","Compact SUV","4","Up to about 75 cu ft with rear seats removed","169.3 in long × 71.6 in wide","2.4-liter four-cylinder","166 hp","All-wheel drive","About 110 mph","About 9.0 seconds","Gasoline","It had airbags, ABS, and stability control; test standards were those of its era.","Its rear seats could fold against the walls or be removed like pieces of furniture.","Honda_Element"),
    H("honda","del-sol","del Sol","1995","VTEC","Targa sports car","2","A small trunk that stores the roof panel","157.7 in long × 66.7 in wide","1.6-liter four-cylinder","160 hp","Front-wheel drive","About 130 mph","About 7.4 seconds","Gasoline","Dual front airbags were offered, but modern crash-rating programs use tougher tests.","Its solid roof panel lifts out so the little coupe becomes open to the sky.","Honda_CR-X_del_Sol"),

    C("toyota","camry","Camry","2025","SE","Midsize hybrid sedan","5","15.1 cu ft trunk","193.5 in long × 72.4 in wide","2.5-liter hybrid four-cylinder","225 hp combined","Front-wheel drive","About 130 mph (estimated)","About 7.0 seconds","Regular gasoline hybrid","For 2025, every U.S. Camry became a hybrid.","Toyota_Camry"),
    C("toyota","corolla","Corolla","2025","LE sedan","Compact sedan","5","13.1 cu ft trunk","182.3 in long × 70.1 in wide","2.0-liter four-cylinder","169 hp","Front-wheel drive","About 118 mph (estimated)","About 8.8 seconds","Regular gasoline","More than 50 million Corollas have been sold around the world.","Toyota_Corolla"),
    C("toyota","rav4","RAV4","2025","XLE","Compact SUV","5","37.6 cu ft behind rear seats","180.9 in long × 73.0 in wide","2.5-liter four-cylinder","203 hp","Front-wheel drive","About 119 mph (estimated)","About 8.0 seconds","Regular gasoline","The original RAV4 helped make small, car-like SUVs popular.","Toyota_RAV4"),
    C("toyota","tacoma","Tacoma","2025","SR5 Double Cab","Midsize pickup","5","Five-foot open cargo bed","213 in long × 76.9 in wide","2.4-liter turbo four-cylinder","278 hp","Rear-wheel drive","About 113 mph (limited)","About 7.0 seconds","Regular gasoline","Some Tacoma trims have shock absorbers built into the front seats for bumpy trails.","Toyota_Tacoma"),
    H("toyota","2000gt","2000GT","1967","MF10","Sports coupe","2","Small luggage area behind seats","164.4 in long × 63.0 in wide","2.0-liter inline-six","150 hp","Rear-wheel drive","About 135 mph","About 8.6 seconds","Gasoline","It had lap belts and disc brakes, but no modern airbags or crash rating.","Only 351 production 2000GTs were built, making it one of Toyota's rarest cars.","Toyota_2000GT"),
    H("toyota","celica","Celica","2000","GT-S","Sport hatchback","4","16.9 cu ft hatch area","170.5 in long × 68.3 in wide","1.8-liter four-cylinder","180 hp","Front-wheel drive","About 140 mph","About 6.6 seconds","Premium gasoline","It offered airbags and ABS, but predates many modern crash tests and driver aids.","Earlier Celicas won rally championships using turbo engines and all-wheel drive.","Toyota_Celica"),
    H("toyota","mr2","MR2","1991","Turbo","Mid-engine sports coupe","2","Small front and rear luggage spaces","164.2 in long × 66.9 in wide","2.0-liter turbo four-cylinder","200 hp","Rear-wheel drive","About 145 mph","About 6.1 seconds","Premium gasoline","Its short wheelbase and mid-engine handling demand care; electronic stability control was absent.","MR2 means mid-engine, rear-wheel drive, two-seater.","Toyota_MR2"),
    H("toyota","fj40","FJ40 Land Cruiser","1978","FJ40","Off-road utility vehicle","4","Simple rear cargo area with folding seats","151.6 in long × 65.6 in wide","4.2-liter inline-six","135 hp","Four-wheel drive","About 85 mph","About 18 seconds","Gasoline","Its rugged body and drum brakes were designed before modern occupant-protection standards.","FJ40s became famous for reaching remote places where roads barely existed.","Toyota_Land_Cruiser_(J40)"),

    C("ford","f-150","F-150","2025","XLT SuperCrew","Full-size pickup","5","5.5-foot open cargo bed","232 in long × 80 in wide","2.7-liter twin-turbo V6","325 hp","Rear-wheel drive","About 110 mph (limited)","About 6.0 seconds","Regular gasoline","An available onboard generator can power tools—or even help during a blackout.","Ford_F-Series"),
    C("ford","mustang","Mustang","2025","GT Fastback","Sports coupe","4","13.5 cu ft trunk","189.4 in long × 75.4 in wide","5.0-liter V8","480 hp","Rear-wheel drive","About 155 mph (limited)","About 4.3 seconds","Premium gasoline recommended","The Mustang has kept its galloping-horse badge since 1964.","Ford_Mustang"),
    C("ford","bronco","Bronco","2025","Big Bend four-door","Off-road SUV","5","35.6 cu ft behind rear seats","189.4 in long × 75.9 in wide","2.3-liter turbo four-cylinder","300 hp","Four-wheel drive","About 100 mph (limited)","About 7.0 seconds","Regular gasoline","Its doors and roof can come off for open-air trail driving.","Ford_Bronco"),
    C("ford","explorer","Explorer","2025","Active","Three-row SUV","7","16.3 cu ft behind third row","198.8 in long × 78.9 in wide","2.3-liter turbo four-cylinder","300 hp","Rear-wheel drive","About 122 mph (estimated)","About 6.0 seconds","Regular gasoline","The Explorer helped turn the family SUV into an American favorite in the 1990s.","Ford_Explorer"),
    H("ford","model-t","Model T","1924","Touring","Open touring car","5","No enclosed trunk","134 in long × about 66 in wide","2.9-liter four-cylinder","20 hp","Rear-wheel drive","About 40–45 mph","More than 20 seconds","Gasoline","It predates seat belts, safety glass, airbags, and crash testing.","Its unusual pedals control low gear, reverse, and braking—not the layout modern drivers know.","Ford_Model_T"),
    H("ford","gt40","GT40","1966","Mk II","Race-bred sports coupe","2","Almost no luggage space","160 in long × 70 in wide","7.0-liter V8","About 485 hp","Rear-wheel drive","Over 200 mph","About 4 seconds","Racing gasoline","Built for racing, with a roll structure but none of a modern road car's active safety aids.","It is only about 40 inches tall—the number in GT40 points to its height.","Ford_GT40"),
    H("ford","thunderbird","Thunderbird","1957","E-code convertible","Personal luxury convertible","2","About 15 cu ft trunk","181.4 in long × 70.3 in wide","5.1-liter V8","270 hp","Rear-wheel drive","About 125 mph","About 7.5 seconds","Gasoline","It was built before federal crash standards and did not have modern restraints.","Ford called it a personal car rather than a sports car.","Ford_Thunderbird_(first_generation)"),
    H("ford","crown-victoria","Crown Victoria","2011","Police Interceptor","Full-size sedan","5","20.6 cu ft trunk","212 in long × 78.3 in wide","4.6-liter V8","250 hp","Rear-wheel drive","About 129 mph","About 8.5 seconds","Gasoline","It used airbags and a strong body-on-frame design, but lacks today's collision-avoidance systems.","Its tough construction made it a longtime favorite for taxis and police fleets.","Ford_Crown_Victoria_Police_Interceptor"),

    C("chevrolet","corvette","Corvette","2025","Stingray 1LT coupe","Mid-engine sports car","2","12.6 cu ft total front/rear cargo","182.3 in long × 76.1 in wide","6.2-liter V8","490 hp","Rear-wheel drive","194 mph","About 2.9 seconds","Premium gasoline","The engine sits behind the seats, but the Corvette still has storage at both ends.","Chevrolet_Corvette_(C8)"),
    C("chevrolet","silverado","Silverado 1500","2025","LT Crew Cab","Full-size pickup","5","Short bed with 62.9 cu ft volume","231.9 in long × 81.2 in wide","5.3-liter V8","355 hp","Rear-wheel drive","About 112 mph (limited)","About 6.1 seconds","Regular gasoline","Its tailgate can fold into steps, a work surface, and several loading positions.","Chevrolet_Silverado"),
    C("chevrolet","equinox","Equinox","2025","LT","Compact SUV","5","29.8 cu ft behind rear seats","183.2 in long × 74.9 in wide","1.5-liter turbo four-cylinder","175 hp","Front-wheel drive","About 120 mph (estimated)","About 8.0 seconds","Regular gasoline","The 2025 version introduced a hidden rear wiper tucked beneath its roof spoiler.","Chevrolet_Equinox"),
    C("chevrolet","tahoe","Tahoe","2025","LT","Full-size SUV","8","25.5 cu ft behind third row","211.3 in long × 81.1 in wide","5.3-liter V8","355 hp","Rear-wheel drive","About 112 mph (limited)","About 7.5 seconds","Regular gasoline","Its independent rear suspension makes room for a much lower, roomier third row.","Chevrolet_Tahoe"),
    H("chevrolet","bel-air","Bel Air","1957","Sport Coupe","Full-size coupe","5","Large traditional trunk","200 in long × 73 in wide","4.6-liter V8","Up to 283 hp","Rear-wheel drive","About 120 mph","About 8 seconds","Gasoline","It predates modern seat-belt rules, airbags, crumple zones, and crash ratings.","The 1957 tail fins and bright chrome made it an instant symbol of 1950s America.","Chevrolet_Bel_Air"),
    H("chevrolet","camaro","Camaro","2024","SS 1LE","Muscle coupe","4","9.1 cu ft trunk","188.3 in long × 74.7 in wide","6.2-liter V8","455 hp","Rear-wheel drive","About 165 mph","About 4.0 seconds","Premium gasoline","It had modern airbags, stability control, and available collision alerts; ratings apply by year and body.","The final sixth-generation Camaro rolled out for the 2024 model year.","Chevrolet_Camaro_(sixth_generation)"),
    H("chevrolet","impala","Impala","2020","Premier","Full-size sedan","5","18.8 cu ft trunk","201.3 in long × 73 in wide","3.6-liter V6","305 hp","Front-wheel drive","About 149 mph","About 6.2 seconds","Gasoline","Its generation included ten airbags and electronic stability control; check its model-year tests.","The Impala name first appeared in 1958 and lasted across ten generations.","Chevrolet_Impala"),
    H("chevrolet","el-camino","El Camino","1970","SS 454","Car-based pickup","3","Open six-foot cargo bed","202 in long × 75.4 in wide","7.4-liter V8","450 hp (period gross rating)","Rear-wheel drive","About 130 mph","About 6 seconds","Gasoline","It predates airbags, stability control, and modern truck crash tests.","It combines the front of a muscle car with a pickup bed behind the seats.","Chevrolet_El_Camino"),

    C("nissan","sentra","Sentra","2025","SV","Compact sedan","5","14.3 cu ft trunk","182.9 in long × 71.5 in wide","2.0-liter four-cylinder","149 hp","Front-wheel drive","About 120 mph (estimated)","About 9.2 seconds","Regular gasoline","The Sentra name has appeared on compact cars since the early 1980s.","Nissan_Sentra"),
    C("nissan","rogue","Rogue","2025","SV","Compact SUV","5","36.5 cu ft behind rear seats","183 in long × 72.4 in wide","1.5-liter variable-compression turbo","201 hp","Front-wheel drive","About 120 mph (estimated)","About 8.0 seconds","Regular gasoline","Its engine can change its compression ratio while running to balance power and efficiency.","Nissan_Rogue"),
    C("nissan","frontier","Frontier","2025","SV Crew Cab","Midsize pickup","5","Five-foot open cargo bed","210.2 in long × 73 in wide","3.8-liter V6","310 hp","Rear-wheel drive","About 112 mph (limited)","About 7.5 seconds","Regular gasoline","Every current Frontier uses a naturally aspirated V6 engine.","Nissan_Frontier_(North_America)"),
    C("nissan","z","Z","2025","Performance","Sports coupe","2","6.9 cu ft hatch area","172.4 in long × 72.6 in wide","3.0-liter twin-turbo V6","400 hp","Rear-wheel drive","155 mph (limited)","About 4.5 seconds","Premium gasoline","Its styling hides clues from several earlier Z cars, including round headlight shapes.","Nissan_Z_(RZ34)"),
    H("nissan","datsun-510","Datsun 510","1971","Two-door sedan","Compact sedan","5","Traditional rear trunk","163 in long × 61.4 in wide","1.6-liter four-cylinder","96 hp","Rear-wheel drive","About 100 mph","About 13 seconds","Gasoline","It had lap-and-shoulder belts in front but no airbags or modern crash structure.","Its simple independent suspension helped make it a giant-killer in racing.","Datsun_510"),
    H("nissan","datsun-240z","Datsun 240Z","1972","Series II","Sports coupe","2","Hatchback luggage shelf","162.8 in long × 64.1 in wide","2.4-liter inline-six","151 hp","Rear-wheel drive","About 125 mph","About 8 seconds","Gasoline","It predates airbags and electronic stability control; its thin pillars reflect its era.","It offered exotic sports-car looks at a price many more drivers could reach.","Nissan_Fairlady_Z_(S30)"),
    H("nissan","300zx","300ZX","1990","Twin Turbo","Sports coupe","2","Small hatch area","169.5 in long × 70.5 in wide","3.0-liter twin-turbo V6","300 hp","Rear-wheel drive","155 mph (limited)","About 5.5 seconds","Premium gasoline","It included a driver's airbag in later years, but predates modern side-impact tests.","Its optional four-wheel-steering system could turn the rear wheels slightly.","Nissan_300ZX"),
    H("nissan","xterra","Xterra","2015","Pro-4X","Off-road SUV","5","36.3 cu ft behind rear seats","178.7 in long × 72.8 in wide","4.0-liter V6","261 hp","Four-wheel drive","About 112 mph","About 7.7 seconds","Gasoline","It had airbags, stability control, and strong contemporary crash-test performance; standards have since advanced.","The stepped roof made extra headroom for rear passengers and carried a distinctive gear basket.","Nissan_Xterra"),

    C("volkswagen","jetta","Jetta","2025","SE","Compact sedan","5","14.1 cu ft trunk","186.5 in long × 70.8 in wide","1.5-liter turbo four-cylinder","158 hp","Front-wheel drive","About 126 mph (estimated)","About 7.1 seconds","Regular gasoline","The Jetta is a sedan cousin of the Golf hatchback.","Volkswagen_Jetta"),
    C("volkswagen","golf-gti","Golf GTI","2025","S","Hot hatchback","5","19.9 cu ft behind rear seats","168.8 in long × 70.4 in wide","2.0-liter turbo four-cylinder","241 hp","Front-wheel drive","155 mph (limited)","About 5.5 seconds","Premium recommended","Its plaid seats and golf-ball-like shifter are playful traditions from the original GTI.","Volkswagen_Golf_Mk8"),
    C("volkswagen","atlas","Atlas","2025","SE","Three-row SUV","7","20.6 cu ft behind third row","200.7 in long × 78.3 in wide","2.0-liter turbo four-cylinder","269 hp","Front-wheel drive","About 115 mph (estimated)","About 7.5 seconds","Regular gasoline","The Atlas was designed especially with North American families and roads in mind.","Volkswagen_Atlas"),
    C("volkswagen","id4","ID.4","2025","Pro","Electric compact SUV","5","30.3 cu ft behind rear seats","180.5 in long × 72.9 in wide","Rear electric motor","282 hp","Rear-wheel drive","About 112 mph","About 5.9 seconds","Electricity","A light strip across the dashboard can glow to help with navigation prompts and charging.","Volkswagen_ID.4"),
    H("volkswagen","beetle","Beetle","1967","Sedan","Compact car","4","Small front trunk plus rear-seat space","160.6 in long × 60.6 in wide","1.5-liter air-cooled flat-four","53 hp","Rear-wheel drive","About 78 mph","About 21 seconds","Gasoline","It was built before airbags, crumple-zone rules, and modern crash ratings.","Its engine is in the back, while the luggage compartment is under the front hood.","Volkswagen_Beetle"),
    H("volkswagen","microbus","Type 2 Microbus","1967","Deluxe","Passenger van","Up to 9","Large flexible passenger/cargo cabin","168.5 in long × 67.7 in wide","1.5-liter air-cooled flat-four","53 hp","Rear-wheel drive","About 65 mph","Over 30 seconds","Gasoline","Its flat front offered little crash space by modern standards and it had no airbags.","The driver sits above the front wheels, making the windshield feel like a moving picture window.","Volkswagen_Type_2"),
    H("volkswagen","karmann-ghia","Karmann Ghia","1967","Coupe","Sporty coupe","4","Small front trunk","163 in long × 64 in wide","1.5-liter air-cooled flat-four","53 hp","Rear-wheel drive","About 82 mph","About 21 seconds","Gasoline","It predates modern restraints, airbags, and crash testing.","Its body was styled in Italy, hand-shaped in Germany, and mounted on Beetle mechanical parts.","Volkswagen_Karmann_Ghia"),
    H("volkswagen","scirocco","Scirocco","1988","16V","Sport hatchback","4","Hatchback cargo area","159.4 in long × 64.5 in wide","1.8-liter four-cylinder","123 hp","Front-wheel drive","About 124 mph","About 8.0 seconds","Gasoline","It predates modern side airbags, stability control, and tougher offset crash tests.","The wedge-shaped Scirocco was named after a hot Mediterranean wind.","Volkswagen_Scirocco"),

    C("bmw","3-series","3 Series","2025","330i","Compact luxury sedan","5","16.9 cu ft trunk","185.9 in long × 71.9 in wide","2.0-liter turbo four-cylinder","255 hp","Rear-wheel drive","130 mph (limited)","About 5.6 seconds","Premium gasoline","The 3 Series has been a core BMW model for half a century.","BMW_3_Series_(G20)"),
    C("bmw","5-series","5 Series","2025","530i","Midsize luxury sedan","5","18.4 cu ft trunk","199.2 in long × 74.8 in wide","2.0-liter turbo mild hybrid","255 hp","Rear-wheel drive","130 mph (limited)","About 5.9 seconds","Premium gasoline","The current 5 Series shares its body shape with the fully electric i5.","BMW_5_Series_(G60)"),
    C("bmw","x3","X3","2025","30 xDrive","Compact luxury SUV","5","31.5 cu ft behind rear seats","187.2 in long × 75.6 in wide","2.0-liter turbo mild hybrid","255 hp","All-wheel drive","130 mph (limited)","About 6.0 seconds","Premium gasoline","BMW calls its SUVs Sports Activity Vehicles.","BMW_X3"),
    C("bmw","x5","X5","2025","xDrive40i","Midsize luxury SUV","5","33.9 cu ft behind rear seats","194.2 in long × 78.9 in wide","3.0-liter turbo inline-six mild hybrid","375 hp","All-wheel drive","130 mph (limited)","About 5.3 seconds","Premium gasoline","Its split tailgate has a small lower section that folds down like a bench.","BMW_X5"),
    H("bmw","2002","2002","1973","tii","Compact sport sedan","4","Traditional rear trunk","166.5 in long × 62.6 in wide","2.0-liter fuel-injected four-cylinder","130 hp","Rear-wheel drive","About 118 mph","About 9 seconds","Gasoline","It predates airbags, ABS, and modern crash tests.","The lively 2002 helped create the idea of a small sports sedan.","BMW_02_Series"),
    H("bmw","e30-m3","E30 M3","1988","Coupe","Homologation sports sedan","4","Traditional rear trunk","171.1 in long × 66.1 in wide","2.3-liter four-cylinder","192 hp","Rear-wheel drive","About 146 mph","About 6.9 seconds","Premium gasoline","It was built before modern airbags and stability control, though its racing shell was very stiff.","BMW widened its body and changed many panels so it could compete in touring-car racing.","BMW_M3"),
    H("bmw","z8","Z8","2001","Roadster","Luxury roadster","2","5.3 cu ft trunk","173.2 in long × 72 in wide","4.9-liter V8","394 hp","Rear-wheel drive","155 mph (limited)","About 4.5 seconds","Premium gasoline","It included airbags, stability control, and a strong aluminum frame; tests were limited by low production.","Every Z8 came with a removable body-color hardtop.","BMW_Z8"),
    H("bmw","isetta","Isetta","1957","300","Bubble microcar","2","Tiny parcel shelf behind seat","90 in long × 54 in wide","298 cc single-cylinder","13 hp","Rear-wheel drive","About 53 mph","More than 30 seconds","Gasoline","It has no airbags, crumple zones, or modern restraints; its front-opening door needs clear space.","The whole front of the car swings open as its only door, steering wheel included.","Isetta"),

    C("mercedes-benz","c-class","C-Class","2025","C 300","Compact luxury sedan","5","12.6 cu ft trunk","187 in long × 74.4 in wide","2.0-liter turbo mild hybrid","255 hp","Rear-wheel drive","130 mph (limited)","About 6.0 seconds","Premium gasoline","Its portrait-shaped center screen borrows ideas from the flagship S-Class.","Mercedes-Benz_C-Class_(W206)"),
    C("mercedes-benz","e-class","E-Class","2025","E 350 4MATIC","Midsize luxury sedan","5","19.1 cu ft trunk","194.9 in long × 74 in wide","2.0-liter turbo mild hybrid","255 hp","All-wheel drive","130 mph (limited)","About 6.1 seconds","Premium gasoline","The grille can be softly illuminated at night on some versions.","Mercedes-Benz_E-Class_(W214)"),
    C("mercedes-benz","gle","GLE","2025","GLE 350 4MATIC","Midsize luxury SUV","5","33.3 cu ft behind rear seats","194.3 in long × 84.9 in wide with mirrors","2.0-liter turbo mild hybrid","255 hp","All-wheel drive","130 mph (limited)","About 7.0 seconds","Premium gasoline","An available suspension can adjust individual wheels to help on rough ground.","Mercedes-Benz_GLE"),
    C("mercedes-benz","g-class","G-Class","2025","G 550","Luxury off-road SUV","5","38.1 cu ft behind rear seats","190 in long × 76 in wide","3.0-liter turbo inline-six mild hybrid","443 hp","All-wheel drive","130 mph (limited)","About 5.3 seconds","Premium gasoline","Three locking differentials help it crawl when one or more wheels lose grip.","Mercedes-Benz_G-Class"),
    H("mercedes-benz","300-sl","300 SL","1955","Gullwing","Sports coupe","2","Luggage shelf behind seats","178 in long × 70.5 in wide","3.0-liter fuel-injected inline-six","215 hp","Rear-wheel drive","About 160 mph","About 8.8 seconds","Gasoline","Its strong spaceframe was advanced, but it predates seat-belt rules, airbags, and crash ratings.","Its roof-hinged gullwing doors exist because tall frame tubes left no room for normal doors.","Mercedes-Benz_300_SL"),
    H("mercedes-benz","190e","190E 2.3-16","1986","Cosworth","Sport sedan","5","Traditional rear trunk","174.6 in long × 66.7 in wide","2.3-liter four-cylinder","167 hp","Rear-wheel drive","About 143 mph","About 7.5 seconds","Gasoline","It offered ABS and a strong safety cell, but predates today's offset and side-impact tests.","A special version set endurance records by driving flat-out for eight days at Nardò.","Mercedes-Benz_W201"),
    H("mercedes-benz","w123-300d","W123 300D","1983","Turbo Diesel","Midsize sedan","5","Traditional rear trunk","186 in long × 70.3 in wide","3.0-liter turbo diesel inline-five","123 hp","Rear-wheel drive","About 103 mph","About 13 seconds","Diesel","Its safety cell and crumple zones were respected for the era, but it lacks modern airbags and aids.","Many W123 taxis traveled enormous distances—some beyond one million miles.","Mercedes-Benz_W123"),
    H("mercedes-benz","ssk","SSK","1929","Roadster","Supercharged sports car","2","Almost no luggage space","About 167 in long","7.1-liter supercharged inline-six","Up to about 300 hp","Rear-wheel drive","About 120 mph","About 10 seconds","Gasoline","It predates enclosed bodies, seat belts, hydraulic crash structures, and rating programs.","SSK is short for the German words meaning Super Sport Short.","Mercedes-Benz_SSK"),

    C("porsche","911","911","2025","Carrera","Rear-engine sports coupe","4","Small front trunk plus rear shelf","178.8 in long × 72.9 in wide","3.0-liter twin-turbo flat-six","388 hp","Rear-wheel drive","183 mph","About 3.9 seconds","Premium gasoline","Its engine still sits behind the rear axle, just as it did in the 1960s.","Porsche_911_(992)"),
    C("porsche","718-cayman","718 Cayman","2025","Cayman","Mid-engine sports coupe","2","Cargo compartments at both ends","172.4 in long × 70.9 in wide","2.0-liter turbo flat-four","300 hp","Rear-wheel drive","170 mph","About 4.9 seconds","Premium gasoline","The mid-engine layout leaves room for a trunk in front and another in back.","Porsche_718_Boxster_and_Cayman_(982)"),
    C("porsche","macan","Macan","2025","Macan 4 Electric","Electric compact SUV","5","18 cu ft rear cargo plus small front trunk","188.3 in long × 76.2 in wide","Dual electric motors","402 hp overboost","All-wheel drive","136 mph","About 4.9 seconds","Electricity","The electric Macan can charge at up to 270 kilowatts under ideal conditions.","Porsche_Macan"),
    C("porsche","cayenne","Cayenne","2025","Cayenne","Midsize luxury SUV","5","27.3 cu ft behind rear seats","194.1 in long × 78.1 in wide","3.0-liter turbo V6","348 hp","All-wheel drive","154 mph","About 5.7 seconds","Premium gasoline","The Cayenne helped prove a sports-car company could build a practical SUV.","Porsche_Cayenne"),
    H("porsche","356","356","1964","C Coupe","Sports coupe","2+2","Small front luggage compartment","155.5 in long × 65.4 in wide","1.6-liter air-cooled flat-four","75 hp","Rear-wheel drive","About 109 mph","About 13.5 seconds","Gasoline","It predates airbags and modern crash testing; early cars had very simple restraints.","It was Porsche's first production automobile.","Porsche_356"),
    H("porsche","944","944","1986","Turbo","Sports hatchback","2+2","Useful rear hatch cargo area","168.9 in long × 68.3 in wide","2.5-liter turbo four-cylinder","217 hp","Rear-wheel drive","About 152 mph","About 5.9 seconds","Premium gasoline","It offered strong brakes and balanced handling, but predates modern airbags and stability control.","A rear-mounted gearbox helped split its weight almost evenly between front and back.","Porsche_944"),
    H("porsche","959","959","1987","Komfort","Supercar","4","Small front luggage area","167.7 in long × 72.4 in wide","2.85-liter twin-turbo flat-six","444 hp","All-wheel drive","197 mph","About 3.7 seconds","Premium gasoline","It had advanced all-wheel drive and ABS, but low production meant no modern public crash rating.","Its computer-controlled all-wheel drive and adjustable suspension seemed futuristic in 1987.","Porsche_959"),
    H("porsche","carrera-gt","Carrera GT","2005","980","Supercar","2","Small removable luggage bags","181.6 in long × 75.6 in wide","5.7-liter V10","605 hp","Rear-wheel drive","205 mph","About 3.9 seconds","Premium gasoline","It used a carbon-fiber structure and airbags but had no stability control; skill was essential.","Its V10 engine began as a racing-engine project before powering this road car.","Porsche_Carrera_GT"),

    C("subaru","outback","Outback","2025","Premium","Adventure wagon","5","32.6 cu ft behind rear seats","191.1 in long × 73 in wide","2.5-liter flat-four","182 hp","All-wheel drive","About 120 mph (estimated)","About 8.6 seconds","Regular gasoline","Its roof rails swing inward to become their own crossbars.","Subaru_Outback"),
    C("subaru","forester","Forester","2025","Premium","Compact SUV","5","29.6 cu ft behind rear seats","183.3 in long × 72 in wide","2.5-liter flat-four","180 hp","All-wheel drive","About 120 mph (estimated)","About 8.5 seconds","Regular gasoline","Large windows and thin roof pillars give drivers an unusually clear view outside.","Subaru_Forester"),
    C("subaru","crosstrek","Crosstrek","2025","Sport","Subcompact SUV","5","19.9 cu ft behind rear seats","176.4 in long × 71.7 in wide","2.5-liter flat-four","182 hp","All-wheel drive","About 120 mph (estimated)","About 8.1 seconds","Regular gasoline","It has 8.7 inches of ground clearance—more than some larger SUVs.","Subaru_Crosstrek"),
    C("subaru","wrx","WRX","2025","Premium","Sport sedan","5","12.5 cu ft trunk","183.8 in long × 71.9 in wide","2.4-liter turbo flat-four","271 hp","All-wheel drive","About 145 mph","About 5.5 seconds","Premium gasoline","The WRX grew from Subaru's mud-slinging World Rally Championship cars.","Subaru_WRX"),
    H("subaru","360","360","1969","Deluxe","Microcar","4","Tiny rear luggage shelf","117.7 in long × 51.1 in wide","356 cc two-cylinder","25 hp","Rear-wheel drive","About 60 mph","About 37 seconds","Gasoline","Its tiny body predates U.S. crash standards and provides very little occupant protection.","It weighed under 1,000 pounds and was nicknamed the ladybug in Japan.","Subaru_360"),
    H("subaru","brat","BRAT","1986","GL","Car-based pickup","2+2","Open cargo bed","174.2 in long × 64.4 in wide","1.8-liter flat-four","73 hp","Four-wheel drive","About 85 mph","About 16 seconds","Gasoline","Its rear-facing bed seats used handles and belts, but riding outside is not acceptable by modern standards.","The name stands for Bi-drive Recreational All-terrain Transporter.","Subaru_BRAT"),
    H("subaru","svx","SVX","1992","LS-L","Grand touring coupe","4","13.0 cu ft trunk","182.1 in long × 69.7 in wide","3.3-liter flat-six","230 hp","All-wheel drive","About 143 mph","About 7.3 seconds","Premium gasoline","It had ABS and a driver's airbag, but predates modern side airbags and offset tests.","Its side windows have smaller windows inside them, like an airplane canopy.","Subaru_Alcyone_SVX"),
    H("subaru","baja","Baja","2006","Turbo","Car-based pickup","4","Short open cargo bed with pass-through","193.3 in long × 70.1 in wide","2.5-liter turbo flat-four","210 hp","All-wheel drive","About 130 mph","About 7.3 seconds","Premium gasoline","It included airbags and ABS, but lacks today's collision-avoidance technology.","A folding panel lets long cargo poke from the bed into the passenger cabin.","Subaru_Baja"),

    C("jeep","wrangler","Wrangler","2025","Sport four-door","Off-road SUV","5","31.7 cu ft behind rear seats","188.4 in long × 73.9 in wide","3.6-liter V6","285 hp","Four-wheel drive","About 110 mph (limited)","About 7.5 seconds","Regular gasoline","Its doors, roof, and even windshield can be removed or folded for open-air adventures.","Jeep_Wrangler_(JL)"),
    C("jeep","grand-cherokee","Grand Cherokee","2025","Laredo","Midsize SUV","5","37.7 cu ft behind rear seats","193.5 in long × 77.5 in wide","3.6-liter V6","293 hp","Rear-wheel drive","About 117 mph (limited)","About 7.4 seconds","Regular gasoline","Available air suspension can raise the body for trails and lower it for highways.","Jeep_Grand_Cherokee_(WL)"),
    C("jeep","compass","Compass","2025","Latitude","Compact SUV","5","27.2 cu ft behind rear seats","173.4 in long × 73.8 in wide","2.0-liter turbo four-cylinder","200 hp","Four-wheel drive","About 120 mph (estimated)","About 7.5 seconds","Regular gasoline","All current U.S. Compass models come with four-wheel drive.","Jeep_Compass"),
    C("jeep","gladiator","Gladiator","2025","Sport","Midsize pickup","5","Five-foot open cargo bed","218 in long × 73.8 in wide","3.6-liter V6","285 hp","Four-wheel drive","About 110 mph (limited)","About 8.0 seconds","Regular gasoline","It is the only new pickup in the U.S. whose doors and roof can come off.","Jeep_Gladiator_(JT)"),
    H("jeep","willys-mb","Willys MB","1944","Military Jeep","Military utility vehicle","4","Open rear utility area","132.3 in long × 62 in wide","2.2-liter four-cylinder","60 hp","Four-wheel drive","About 65 mph","About 23 seconds","Gasoline","It was a wartime tool with no airbags, crumple zones, doors, or modern restraints.","Its flat body could be shipped, repaired, and adapted for countless wartime jobs.","Willys_MB"),
    H("jeep","cj5","CJ-5","1976","Renegade","Off-road utility vehicle","4","Small open rear cargo area","138.2 in long × 65.3 in wide","5.0-liter V8","150 hp","Four-wheel drive","About 90 mph","About 12 seconds","Gasoline","Its short wheelbase, high center of gravity, and basic restraints require much more care than a modern SUV.","The CJ-5 stayed in production for nearly three decades.","Jeep_CJ"),
    H("jeep","cherokee-xj","Cherokee XJ","1997","Sport four-door","Compact SUV","5","32.9 cu ft behind rear seats","167.5 in long × 67.9 in wide","4.0-liter inline-six","190 hp","Four-wheel drive","About 112 mph","About 9 seconds","Gasoline","Later examples had front airbags and ABS options, but their structure predates current crash tests.","Its one-piece body was lighter and roomier than many body-on-frame rivals.","Jeep_Cherokee_(XJ)"),
    H("jeep","grand-wagoneer-sj","Grand Wagoneer SJ","1991","Grand Wagoneer","Full-size luxury SUV","6","Large rear cargo area","186.5 in long × 75.6 in wide","5.9-liter V8","144 hp","Four-wheel drive","About 100 mph","About 14 seconds","Gasoline","It had basic belts but no airbags or modern electronic safety systems.","Its famous wood-look sides helped make a rugged 4×4 feel like a luxury family wagon.","Jeep_Wagoneer_(SJ)")
  ];
}());
