(function () {
  const NHTSA = "https://www.nhtsa.gov/ratings";
  const IIHS = "https://www.iihs.org/ratings";
  const safety = {
    mazda:"Includes Mazda i-Activsense driver-assistance features; official crash results depend on build date and trim.",
    honda:"Includes Honda Sensing driver assistance; check the exact body style and model year in official crash tests.",
    toyota:"Includes Toyota Safety Sense; official ratings can differ by drivetrain and body style.",
    ford:"Includes Ford Co-Pilot360 features; official ratings apply only to the tested configuration.",
    chevrolet:"Includes Chevy Safety Assist features; body, battery, and drivetrain can change a vehicle's rating.",
    nissan:"Includes Nissan Safety Shield 360 features; check official results for the exact configuration.",
    volkswagen:"Includes automatic emergency braking and IQ.DRIVE features; ratings vary by version.",
    bmw:"Offers modern active-safety and driver-assistance systems; ratings vary by options and body style.",
    "mercedes-benz":"Offers modern active braking and driver-assistance systems; ratings vary by configuration.",
    porsche:"Uses modern airbags, stability control, and available driver aids; not every low-volume sports car is crash-rated.",
    subaru:"Includes EyeSight driver assistance on most versions; transmission and trim can affect availability.",
    jeep:"Includes modern airbags and active-safety aids; ratings vary by body and drivetrain."
  };
  const M = (make, id, name, year, trim, type, seats, interior, size, power, horsepower, drivetrain, topSpeed, acceleration, fuel, coolFact, wikiTitle, officialUrl) => ({
    slug:`${make}-${id}`, make, name, era:"current", year, trim, type, seats, interior, size, power, horsepower, drivetrain, topSpeed, acceleration, fuel,
    safety:safety[make], coolFact, wikiTitle,
    sources:[{label:"Manufacturer specifications",url:officialUrl},{label:"NHTSA ratings",url:NHTSA},{label:"IIHS ratings",url:IIHS}]
  });
  window.CARS.push(
    M("mazda","cx-50","CX-50","2026","2.5 S Select","Compact SUV","5","31.4 cu ft behind rear seats","185.8 in long × 75.6 in wide","2.5-liter four-cylinder","187 hp","All-wheel drive","About 125 mph (estimated)","About 8.0 seconds","Regular gasoline","Its wide roof is designed to make outdoor gear easier to reach.","Mazda_CX-50","https://www.mazdausa.com/vehicles/cx-50/compare-vehicle-specs-and-trims"),
    M("mazda","cx-70","CX-70","2026","3.3 Turbo Preferred","Midsize SUV","5","39.6 cu ft behind rear seats","201.6 in long × 77.6 in wide","3.3-liter turbo inline-six mild hybrid","280 hp","All-wheel drive","About 130 mph (estimated)","About 6.8 seconds","Regular gasoline","Hidden storage beneath the cargo floor is shaped to hold small valuables and emergency gear.","Mazda_CX-70","https://www.mazdausa.com/vehicles/cx-70"),
    M("mazda","cx-90","CX-90","2026","3.3 Turbo Select","Three-row SUV","8","14.9 cu ft behind third row","201.6 in long × 77.6 in wide","3.3-liter turbo inline-six mild hybrid","280 hp","All-wheel drive","About 130 mph (estimated)","About 6.5 seconds","Regular gasoline","Mazda's largest U.S. vehicle can carry up to eight people.","Mazda_CX-90","https://www.mazdausa.com/vehicles/cx-90"),
    M("mazda","mazda3-sedan","Mazda3 Sedan","2026","2.5 S","Compact sedan","5","13.2 cu ft trunk","183.5 in long × 70.7 in wide","2.5-liter four-cylinder","186 hp","Front-wheel drive","About 130 mph (estimated)","About 7.2 seconds","Regular gasoline","It shares its name and dashboard with the hatchback but has a separate trunk and longer body.","Mazda3","https://www.mazdausa.com/vehicles/mazda3-sedan/compare-vehicle-specs-and-trims"),

    M("honda","hr-v","HR-V","2026","LX","Subcompact SUV","5","24.4 cu ft behind rear seats","179.8 in long × 72.4 in wide","2.0-liter four-cylinder","158 hp","Front-wheel drive","About 115 mph (estimated)","About 9.4 seconds","Regular gasoline","The current HR-V uses the same basic platform family as the Civic.","Honda_HR-V","https://automobiles.honda.com/2026/hr-v/specs-features-trim-comparison"),
    M("honda","passport","Passport","2026","RTL","Midsize SUV","5","44 cu ft behind rear seats","191.5 in long × 79.5 in wide","3.5-liter V6","285 hp","All-wheel drive","About 112 mph (limited)","About 6.8 seconds","Regular gasoline","A hidden compartment beneath the cargo floor can hold muddy or wet gear.","Honda_Passport","https://automobiles.honda.com/passport"),
    M("honda","odyssey","Odyssey","2026","EX-L","Minivan","8","32.8 cu ft behind third row","205.2 in long × 78.5 in wide","3.5-liter V6","280 hp","Front-wheel drive","About 111 mph (limited)","About 6.5 seconds","Regular gasoline","Its middle-row seats can slide sideways as well as forward and back.","Honda_Odyssey_(North_America)","https://automobiles.honda.com/odyssey/specs-features-trim-comparison"),
    M("honda","ridgeline","Ridgeline","2026","Sport","Midsize pickup","5","5.3-foot bed plus 7.3 cu ft in-bed trunk","210.2 in long × 78.6 in wide","3.5-liter V6","280 hp","All-wheel drive","About 112 mph (limited)","About 6.3 seconds","Regular gasoline","Its lockable trunk is hidden beneath the pickup bed and even has a drain plug.","Honda_Ridgeline","https://automobiles.honda.com/ridgeline/specs-features-trim-comparison"),

    M("toyota","prius","Prius","2026","LE","Hybrid hatchback","5","23.8 cu ft cargo behind rear seats","181.1 in long × 70.2 in wide","2.0-liter hybrid four-cylinder","194 hp combined","Front-wheel drive","About 115 mph","About 7.2 seconds","Regular gasoline hybrid","Its slippery shape uses hidden rear door handles to help air glide past.","Toyota_Prius","https://www.toyota.com/prius/"),
    M("toyota","4runner","4Runner","2026","SR5","Off-road SUV","5","48.4 cu ft behind rear seats","194.9 in long × 77.8 in wide","2.4-liter turbo four-cylinder","278 hp","Rear-wheel drive","About 115 mph (estimated)","About 7.5 seconds","Regular gasoline","The rear window can roll down into the tailgate.","Toyota_4Runner","https://www.toyota.com/4runner/"),
    M("toyota","highlander","Highlander","2026","LE","Three-row SUV","8","16 cu ft behind third row","194.9 in long × 76 in wide","2.4-liter turbo four-cylinder","265 hp","Front-wheel drive","About 118 mph (estimated)","About 7.5 seconds","Regular gasoline","Its third row folds flat to turn passenger space into a long cargo floor.","Toyota_Highlander","https://www.toyota.com/highlander/"),
    M("toyota","sienna","Sienna","2026","LE","Hybrid minivan","8","33.5 cu ft behind third row","203.7 in long × 78.5 in wide","2.5-liter hybrid four-cylinder","245 hp combined","Front-wheel drive","About 116 mph (estimated)","About 7.9 seconds","Regular gasoline hybrid","Every current Sienna is a hybrid, and all-wheel drive is available.","Toyota_Sienna","https://www.toyota.com/sienna/"),

    M("ford","escape","Escape","2026","Active","Compact SUV","5","37.5 cu ft behind rear seats","181.2 in long × 74.1 in wide","1.5-liter turbo three-cylinder","180 hp","Front-wheel drive","About 120 mph (estimated)","About 7.7 seconds","Regular gasoline","Its sliding rear seat lets families choose between extra legroom and extra cargo room.","Ford_Escape","https://www.ford.com/suvs-crossovers/escape/"),
    M("ford","expedition","Expedition","2026","Active","Full-size SUV","8","22.9 cu ft behind third row","209.9 in long × 80 in wide","3.5-liter twin-turbo V6","400 hp","Rear-wheel drive","About 115 mph (limited)","About 5.8 seconds","Regular gasoline","Its split tailgate opens as both a liftgate and a small work bench.","Ford_Expedition","https://www.ford.com/suvs/expedition/"),
    M("ford","maverick","Maverick","2026","XL Hybrid","Compact pickup","5","4.5-foot open cargo bed","199.8 in long × 72.6 in wide","2.5-liter hybrid four-cylinder","191 hp combined","Front-wheel drive","About 110 mph (limited)","About 7.7 seconds","Regular gasoline hybrid","Slots in its bed let owners divide cargo with ordinary pieces of lumber.","Ford_Maverick_(2022)","https://www.ford.com/trucks/maverick/"),
    M("ford","ranger","Ranger","2026","XLT SuperCrew","Midsize pickup","5","Five-foot open cargo bed","210.6 in long × 75.5 in wide","2.3-liter turbo four-cylinder","270 hp","Rear-wheel drive","About 110 mph (limited)","About 6.5 seconds","Regular gasoline","A built-in step beside the rear bumper makes climbing into the bed easier.","Ford_Ranger_(Americas)","https://www.ford.com/trucks/ranger/"),

    M("chevrolet","trax","Trax","2026","LT","Subcompact SUV","5","25.6 cu ft behind rear seats","178.6 in long × 71.8 in wide","1.2-liter turbo three-cylinder","137 hp","Front-wheel drive","About 115 mph (estimated)","About 8.8 seconds","Regular gasoline","Despite its name, it is longer and roomier than the earlier Trax generation.","Chevrolet_Trax","https://www.chevrolet.com/suvs/trax"),
    M("chevrolet","trailblazer","Trailblazer","2026","LT","Subcompact SUV","5","25.3 cu ft behind rear seats","174.1 in long × 71.2 in wide","1.3-liter turbo three-cylinder","155 hp","Front-wheel drive","About 120 mph (estimated)","About 8.7 seconds","Regular gasoline","Its front passenger seat can fold flat to carry objects nearly nine feet long.","Chevrolet_Trailblazer_(crossover)","https://www.chevrolet.com/suvs/trailblazer"),
    M("chevrolet","traverse","Traverse","2026","LT","Three-row SUV","8","22.9 cu ft behind third row","204.5 in long × 79.6 in wide","2.5-liter turbo four-cylinder","328 hp","Front-wheel drive","About 130 mph (estimated)","About 6.8 seconds","Regular gasoline","It offers more than 97 cu ft of cargo room when both rear rows are folded.","Chevrolet_Traverse","https://www.chevrolet.com/suvs/traverse"),
    M("chevrolet","blazer-ev","Blazer EV","2026","LT FWD","Electric midsize SUV","5","25.5 cu ft behind rear seats","192.2 in long × 78 in wide","Single electric motor","220 hp","Front-wheel drive","About 118 mph","About 7.5 seconds","Electricity","Its flat battery lives beneath the cabin and helps create a long wheelbase.","Chevrolet_Blazer_EV","https://www.chevrolet.com/electric/blazer-ev"),

    M("nissan","kicks","Kicks","2026","SV","Subcompact SUV","5","30 cu ft behind rear seats","171.9 in long × 70.9 in wide","2.0-liter four-cylinder","141 hp","Front-wheel drive","About 115 mph (estimated)","About 9.5 seconds","Regular gasoline","The newest Kicks offers all-wheel drive for the first time.","Nissan_Kicks","https://www.nissanusa.com/vehicles/crossovers-suvs/kicks.html"),
    M("nissan","murano","Murano","2026","SV","Midsize SUV","5","32.9 cu ft behind rear seats","192.9 in long × 78 in wide","2.0-liter variable-compression turbo","241 hp","Front-wheel drive","About 120 mph (estimated)","About 7.5 seconds","Regular gasoline","Its engine can change shape inside to balance power and efficiency.","Nissan_Murano","https://www.nissanusa.com/vehicles/crossovers-suvs/murano.html"),
    M("nissan","pathfinder","Pathfinder","2026","SV","Three-row SUV","8","16.6 cu ft behind third row","197.7 in long × 77.9 in wide","3.5-liter V6","284 hp","Front-wheel drive","About 120 mph (estimated)","About 7.0 seconds","Regular gasoline","Its second-row seats can tilt forward even when a child seat is attached.","Nissan_Pathfinder","https://www.nissanusa.com/vehicles/crossovers-suvs/pathfinder.html"),
    M("nissan","armada","Armada","2026","SV","Full-size SUV","8","20.4 cu ft behind third row","209.6 in long × 80 in wide","3.5-liter twin-turbo V6","425 hp","Rear-wheel drive","About 130 mph (estimated)","About 6.2 seconds","Regular gasoline","The newest Armada traded its old V8 for a more powerful twin-turbo V6.","Nissan_Armada","https://www.nissanusa.com/vehicles/crossovers-suvs/armada.html"),

    M("volkswagen","taos","Taos","2026","SE","Subcompact SUV","5","27.9 cu ft behind rear seats","175.9 in long × 72.5 in wide","1.5-liter turbo four-cylinder","174 hp","Front-wheel drive","About 125 mph (estimated)","About 7.4 seconds","Regular gasoline","It is Volkswagen's smallest U.S. SUV but has a surprisingly boxy cargo area.","Volkswagen_Taos","https://www.vw.com/en/models/taos.html"),
    M("volkswagen","tiguan","Tiguan","2026","SE","Compact SUV","5","33.8 cu ft behind rear seats","184.4 in long × 73 in wide","2.0-liter turbo four-cylinder","201 hp","Front-wheel drive","About 125 mph (estimated)","About 7.5 seconds","Regular gasoline","Its available screen is 15 inches across—nearly as wide as a school ruler is long.","Volkswagen_Tiguan","https://www.vw.com/en/models/tiguan.html"),
    M("volkswagen","id-buzz","ID. Buzz","2025","Pro S","Electric minivan","7","18.6 cu ft behind third row","195.4 in long × 78.1 in wide","Rear electric motor","282 hp","Rear-wheel drive","99 mph (limited)","About 7.5 seconds","Electricity","Its two-tone shape reimagines the classic VW Microbus for the electric age.","Volkswagen_ID._Buzz","https://www.vw.com/en/models/id-buzz.html"),
    M("volkswagen","golf-r","Golf R","2026","Hatchback","Hot hatchback","5","19.9 cu ft behind rear seats","168.9 in long × 70.4 in wide","2.0-liter turbo four-cylinder","328 hp","All-wheel drive","155 mph (limited)","About 4.5 seconds","Premium gasoline","A special Drift mode can send extra power toward an outside rear wheel on a closed course.","Volkswagen_Golf_Mk8","https://www.vw.com/en/models/golf-r.html"),

    M("bmw","2-series","2 Series","2026","230i Coupe","Compact luxury coupe","4","13.8 cu ft trunk","179 in long × 72.4 in wide","2.0-liter turbo four-cylinder","255 hp","Rear-wheel drive","130 mph (limited)","About 5.5 seconds","Premium gasoline","It is one of the few small coupes still available with rear-wheel drive.","BMW_2_Series_(G42)","https://www.bmwusa.com/vehicles/2-series/coupe/overview.html"),
    M("bmw","7-series","7 Series","2026","740i","Full-size luxury sedan","5","19.1 cu ft trunk","212.2 in long × 76.8 in wide","3.0-liter turbo inline-six mild hybrid","375 hp","Rear-wheel drive","130 mph (limited)","About 5.2 seconds","Premium gasoline","An available 31-inch theater screen folds down from the ceiling for rear passengers.","BMW_7_Series_(G70)","https://www.bmwusa.com/vehicles/7-series/sedan/overview.html"),
    M("bmw","x1","X1","2026","xDrive28i","Subcompact luxury SUV","5","25.7 cu ft behind rear seats","177.2 in long × 72.6 in wide","2.0-liter turbo four-cylinder","241 hp","All-wheel drive","130 mph (limited)","About 6.2 seconds","Premium gasoline","It is BMW's smallest SUV but has a tall, flexible cargo area.","BMW_X1_(U11)","https://www.bmwusa.com/vehicles/x-models/x1/sports-activity-vehicle/overview.html"),
    M("bmw","i4","i4","2026","eDrive40","Electric sport sedan","5","About 16.6 cu ft hatch cargo","188.5 in long × 72.9 in wide","Rear electric motor","335 hp","Rear-wheel drive","118 mph","About 5.5 seconds","Electricity","Its hatchback hides beneath a roofline that looks like a sleek sedan.","BMW_i4","https://www.bmwusa.com/vehicles/all-electric/i4/gran-coupe/overview.html"),

    M("mercedes-benz","cla","CLA","2026","CLA 250 4MATIC","Compact luxury coupe-style sedan","5","11.6 cu ft trunk","184.6 in long × 72 in wide","2.0-liter turbo mild hybrid","221 hp","All-wheel drive","130 mph (limited)","About 6.3 seconds","Premium gasoline","Its four doors hide beneath a roofline shaped like a coupe.","Mercedes-Benz_CLA-Class","https://www.mbusa.com/en/vehicles/class/cla/coupe"),
    M("mercedes-benz","s-class","S-Class","2026","S 500 4MATIC","Full-size luxury sedan","5","12.9 cu ft trunk","208.2 in long × 76.9 in wide","3.0-liter turbo inline-six mild hybrid","442 hp","All-wheel drive","130 mph (limited)","About 4.5 seconds","Premium gasoline","The S-Class has introduced technologies that later spread to ordinary cars.","Mercedes-Benz_S-Class_(W223)","https://www.mbusa.com/en/vehicles/class/s-class/sedan"),
    M("mercedes-benz","eqe-sedan","EQE Sedan","2025","EQE 350+","Electric luxury sedan","5","15 cu ft trunk","196.9 in long × 75 in wide","Rear electric motor","288 hp","Rear-wheel drive","130 mph","About 6.2 seconds","Electricity","Its smooth one-bow roof helps it slip quietly through the air.","Mercedes-Benz_EQE","https://www.mbusa.com/en/vehicles/class/eqe/sedan"),
    M("mercedes-benz","gls","GLS","2026","GLS 450 4MATIC","Full-size luxury SUV","7","17.4 cu ft behind third row","205 in long × 79.9 in wide","3.0-liter turbo inline-six mild hybrid","375 hp","All-wheel drive","130 mph (limited)","About 5.8 seconds","Premium gasoline","Its air suspension can lower the body to make loading people or cargo easier.","Mercedes-Benz_GLS","https://www.mbusa.com/en/vehicles/class/gls/suv"),

    M("porsche","718-boxster","718 Boxster","2025","Boxster","Roadster","2","Cargo compartments at both ends","172.4 in long × 70.9 in wide","2.0-liter turbo flat-four","300 hp","Rear-wheel drive","171 mph","About 4.7 seconds","Premium gasoline","Its name mixes boxer engine with roadster.","Porsche_718_Boxster_and_Cayman_(982)","https://www.porsche.com/usa/models/718/"),
    M("porsche","taycan","Taycan","2027","Taycan","Electric sport sedan","4","Front trunk plus rear luggage area","195.4 in long × 77.5 in wide","Rear electric motor","402 hp","Rear-wheel drive","143 mph","About 4.5 seconds","Electricity","Its rear motor uses a two-speed gearbox—unusual for an electric car.","Porsche_Taycan","https://www.porsche.com/usa/models/taycan/"),
    M("porsche","panamera","Panamera","2027","Panamera","Luxury sport sedan","4+1","Large hatchback cargo area","198.9 in long × 76.3 in wide","2.9-liter twin-turbo V6","348 hp","Rear-wheel drive","169 mph","About 5.0 seconds","Premium gasoline","Its rear hatch opens with the back window, giving it sports-car looks and useful cargo access.","Porsche_Panamera","https://www.porsche.com/usa/models/panamera/"),
    M("porsche","cayenne-coupe","Cayenne Coupe","2026","Cayenne Coupe","Coupe-style SUV","4+1","About 20 cu ft behind rear seats","194.2 in long × 78.1 in wide","3.0-liter turbo V6","348 hp","All-wheel drive","154 mph","About 5.7 seconds","Premium gasoline","Its lower roof and faster rear window turn the practical Cayenne into a sleeker shape.","Porsche_Cayenne","https://www.porsche.com/usa/models/cayenne/cayenne-coupe-models/"),

    M("subaru","impreza","Impreza","2026","Sport","Compact hatchback","5","20.4 cu ft behind rear seats","176.2 in long × 70.1 in wide","2.0-liter flat-four","152 hp","All-wheel drive","About 125 mph (estimated)","About 9.0 seconds","Regular gasoline","Every current Impreza sends power to all four wheels.","Subaru_Impreza","https://www.subaru.com/vehicles/impreza.html"),
    M("subaru","brz","BRZ","2026","Premium","Sports coupe","4","6.3 cu ft trunk","167.9 in long × 69.9 in wide","2.4-liter flat-four","228 hp","Rear-wheel drive","About 140 mph","About 5.5 seconds","Premium gasoline","Unlike most Subarus, the BRZ uses rear-wheel drive for playful sports-car handling.","Subaru_BRZ","https://www.subaru.com/vehicles/brz.html"),
    M("subaru","ascent","Ascent","2026","Premium","Three-row SUV","8","17.8 cu ft behind third row","196.8 in long × 76 in wide","2.4-liter turbo flat-four","260 hp","All-wheel drive","About 130 mph (estimated)","About 6.8 seconds","Regular gasoline","It is the largest vehicle Subaru sells in North America.","Subaru_Ascent","https://www.subaru.com/vehicles/ascent.html"),
    M("subaru","solterra","Solterra","2026","Premium","Electric compact SUV","5","23.8 cu ft behind rear seats","184.6 in long × 73.2 in wide","Dual electric motors","233 hp","All-wheel drive","About 100 mph","About 6.5 seconds","Electricity","Its name combines the Latin words for sun and earth.","Subaru_Solterra","https://www.subaru.com/vehicles/solterra.html"),

    M("jeep","wagoneer","Wagoneer","2025","Series II","Full-size SUV","8","27.4 cu ft behind third row","214.7 in long × 83.6 in wide","3.0-liter twin-turbo inline-six","420 hp","Rear-wheel drive","About 118 mph (limited)","About 6.3 seconds","Regular gasoline","Its long-wheelbase version has an enormous 44.2 cu ft behind the third row.","Jeep_Wagoneer_(WS)","https://www.jeep.com/wagoneer/wagoneer.html"),
    M("jeep","grand-wagoneer","Grand Wagoneer","2026","Grand Wagoneer","Full-size luxury SUV","8","27.4 cu ft behind third row","214.7 in long × 83.6 in wide","3.0-liter twin-turbo inline-six","540 hp","Four-wheel drive","About 118 mph (limited)","About 5.9 seconds","Premium gasoline","With available displays, its cabin can contain more than 75 inches of total screen area.","Jeep_Grand_Wagoneer_(WS)","https://www.jeep.com/wagoneer/2026/grand-wagoneer.html"),
    M("jeep","wagoneer-s","Wagoneer S","2025","Launch Edition","Electric midsize SUV","5","30.6 cu ft behind rear seats","192.4 in long × 74.8 in wide","Dual electric motors","600 hp","All-wheel drive","124 mph","About 3.4 seconds","Electricity","Its seven-slot grille is closed because an electric motor needs much less cooling air.","Jeep_Wagoneer_S","https://www.jeep.com/wagoneer/wagoneer-s.html"),
    M("jeep","cherokee","Cherokee","2026","Laredo","Midsize hybrid SUV","5","About 33.6 cu ft behind rear seats","188.1 in long × 74.4 in wide","1.6-liter turbo hybrid","210 hp combined","Four-wheel drive","About 115 mph (estimated)","About 8 seconds (estimated)","Regular gasoline hybrid","The Cherokee name returned for 2026 on a larger hybrid-only model.","Jeep_Cherokee","https://www.jeep.com/2026/cherokee.html")
  );
}());
